### ISSUE TITLE
Accessing Arrays - placement of index

### ISSUE THREAD

**Issue by proddata** [crate/crate#10110]
###  Documentation feedback

 
- Page title: Selecting data
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/dql/selects.html
- Source: https://github.com/crate/crate/blob/master/docs/general/dql/selects.rst

---

From the documentation it is unclear how to correctly access arrays within objects.
The example has the index right after the identifier, but it is not clear if information is an object or array:
```SQL
select name, information[1]['population'] as population from locations
... where information['population'] is not null
... order by name;
```

Putting the index first look unintuitive 
```SQL
CREATE TABLE test (a OBJECT);
insert into a values({ id = 1, name = 'foo', tags = ['apple', 'banana', 'pear'], size = 3.1415, valid = true });

SELECT a FROM test limit 100;
-- SELECT OK, 1 row in set (0.005 sec)

SELECT a[1]['tags'] FROM test limit 100;
-- SELECT a[1]['tags'] FROM test limit 100; --> apple

SELECT a['tags'][1] FROM test LIMIT 100;
-- SQLActionException[UnsupportedFeatureException: Nested array access is not supported]
```

**Comment by mechanomi** [comment]
thanks for the feedback, @proddata!

**Comment by mfussenegger** [comment]
@mechanomi I think this is something where we can also look into changing the behavior or support both versions. 

This is indeed rather unintuitive:

```
cr> SELECT a['tags'] FROM test limit 100;
+-----------------------------+
| a['tags']                   |
+-----------------------------+
| ["apple", "banana", "pear"] |
+-----------------------------+
SELECT 1 row in set (0.007 sec)
cr> SELECT ['apple', 'banana', 'pear'][1] FROM test limit 100;
+---------+
| 'apple' |
+---------+
| apple   |
+---------+
SELECT 1 row in set (0.005 sec)
```

**Comment by mechanomi** [comment]
relabeled this as a docs correction. will spin off an issue re supporting both versions (and will restore your original labels to that issue)

**Comment by proddata** [comment]
@mechanomi did you create the feature issue?

**Comment by mechanomi** [comment]
@proddata my bad! here you go:

https://github.com/crate/crate/issues/10322

**Comment by mechanomi** [comment]
I started work on this today. I thought it was going to be a quick fix (perhaps a small admonition block or something) but the work has expanded

the first issue I found was that the actual data being queried is not shown. there *are* examples showing inserts, but the actual data being selected and queried is from the test harness. to address this, I started to rework the examples so that the reader is first shown the data and is then shown how it can be selected and queried

however, this wasn't sufficient. even with updated examples and better prose, the content is poorly organized and confusing as a result. this issue is exacerbated by the fact that

- Arrays and objects can be nested
- There is a special syntax for querying a single property of all objects within an array that looks identical to querying a single object property

that last point was new information to me. the docs do not explain this very well and it took some practical experimentation to figure out

to address this, I have overhauled the bits of `selects.html` that cover arrays, objects, and their nested permutations

originally, this was going to go into https://github.com/crate/crate/pull/10861, but the scope of these changes has prompted me to spin it out a separate PR (currently a draft). this is in progress

--

a small footnote

the test data is themed around locations from The Hitchhikers Guide to the Galaxy and associates a number of fictional "locations" and "races" (which is fine, in my view). however, the main text confuses things by adding European cities to this data and in one instance identifies "Vorarlberger" as a "race"

this terminology is inaccurate and poorly chosen. I have replaced all instances of "race" with "inhabitants", which works in both contexts

I had to introduce two extra locations while expanding the examples and went with European city names for consistency with the surrounding text. however, having written this, I should probably replace all instances of European city names with additional locations from The Hitchhikers Guide to the Galaxy. the mixing of themes adds unnecessary confusion to an already challenging topic

**Comment by mechanomi** [comment]
I am closing this issue as done now that https://github.com/crate/crate/pull/10866 has been merged

you would be able to see the changes on the live site, but unfortunately, the `master` URL version is broken atm (fix pending at https://github.com/crate/salt/pull/2492). fortunately, you can view staging docs on RTD:

this whole section has been reworked:

https://crate.readthedocs.io/en/latest/general/dql/selects.html#nonscalar-data-types

would be interested in a general review on this. does it read better? flow better? make more sense, and so on?

but, specifically, to close this issue:

-  @proddata please check out the https://crate.readthedocs.io/en/latest/general/dql/selects.html#nested-structures section and let me know if it addresses your original criticism
  
-  @mfussenegger check out https://crate.readthedocs.io/en/latest/general/dql/selects.html#limitations and see if that captures what you were suggesting

---

in case you're bored, there is a lot of details on https://github.com/crate/crate/pull/10866. or, perhaps more usefully, a reasonably detailed summary in the commit message: https://github.com/crate/crate/pull/10866/commits/9b7c9d16f5b5762b7b7777e61687ed049345322e

**Comment by proddata** [comment]
@mechanomi 

Looks good to me.

Though I think there is a small typing error `Lucine` instead of `Lucene` in the **Limitations** section ... can't find the pr

**Comment by mechanomi** [comment]
thanks for the review, @proddata! will close this issue

https://github.com/crate/crate/pull/10951 addresses the spelling mistake. good catch ty!

**Comment by mfussenegger** [comment]
> check out https://crate.readthedocs.io/en/latest/general/dql/selects.html#limitations and see if that captures what you were suggesting

I think the reasoning is not fully correct. The `array(array(..))` limitation is not related to the flattening of the index structure. I don't remember the real reason for the limitation, I think by now it might actually be mostly artificial.

The oddity with the placement of the array index in `inhabitants[1]['interests']` is also not related to the flattened index structure, but had to do with our type system and how we represent functions internally.

**Comment by mechanomi** [comment]
@mfussenegger ah. hmm. thx! I'll reopen and take another look

**Comment by mechanomi** [comment]
this is complete now
