### ISSUE TITLE
Error when joining two VIEWs with objects

### ISSUE THREAD

**Issue by proddata** [crate/crate#10116]
**CrateDB version**:
4.1.6 (CrateDB Cloud)

**Environment description**:

CrateDB Cloud (A1)

**Problem description**:

When trying to join two views an error gets thrown. Joining both original tables works fine though

**Steps to reproduce**:

setup works fine:
```SQL
CREATE TABLE IF NOT EXISTS "test"."m1" (
   "text1" TEXT,
   "obj1" OBJECT(DYNAMIC) AS (
      "text2" TEXT,
      "arr1" ARRAY(OBJECT(DYNAMIC) AS (
         "text3" TEXT,
         "text4" TEXT
      )
      )
   )
);

CREATE TABLE IF NOT EXISTS "test"."m2" (
   "text1" TEXT,
   "obj1" OBJECT(DYNAMIC) AS (
      "text2" TEXT,
      "arr1" ARRAY(OBJECT(DYNAMIC) AS (
         "text3" TEXT,
         "text4" TEXT
      )
      )
   )
);

create or replace view test.v1 as
 select 
 text1,
 obj1[1]['arr1']['text3'] as val1
 from test.m1;

create or replace view test.v2 as
 select 
 text1 as t1,
 obj1[1]['arr1']['text3'] as val1
 from test.m2;
```

JOIN with original tables works fine:
```SQL
SELECT vv1.*, vv2.* FROM "test"."m1" vv1, "test"."m2" vv2 limit 100;
-- SELECT OK, 0 rows in set (0.004 sec)
```

JOIN on views throws error:
```SQL
SELECT vv1.*, vv2.* FROM "test"."v1" vv1, "test"."v2" vv2 limit 100;
-- Error!
-- SQLActionException[UnsupportedFeatureException: Can't handle Symbol obj1['arr1']['text3']]
```

**Comment by mfussenegger** [comment]
Thank you for the report.
The examples work on master/4.2 and this has a similar root cause as https://github.com/crate/crate/issues/10108 and the fix is similar in scope which is why we also won't be creating a fix within 4.1 for this.

Unfortunately in this case there is also no good workaround. We try to avoid leaving bug reports for the current stable version unfixed within that minor version, but in this case the root issue led to the refactorings and they're simply too invasive for a backport.

On the plus side, we should have 4.2 out pretty soon.
