### ISSUE TITLE
Rename column

### ISSUE THREAD

**Issue by Kaban77** [crate/crate#10297]
Hi!
Can you add functionality to rename columns?

**Comment by mfussenegger** [comment]
We talked a bit about this shortly. Overall we understand and agree that this would be an important feature.

This is a bit related to https://github.com/crate/crate/issues/4457 and https://github.com/crate/crate/issues/9238

Some of the challenges:

- Changing the name for new document would be easy, the problem is how to handle old data and what happens if you want to re-use the old name with a different data type
- Column names are currently part of the source (that means part of the data itself). If we worked on https://github.com/crate/crate/issues/10025 first that would make things a bit easier. One idea is to then make the column names mostly virtual and map them to internal "storage slots". Then a rename would be as simple as changing the virtual name and updating the storage slot pointer.
