### ISSUE TITLE
CrateDB fails to start on Windows Server without Microsoft Visual C++ 2010 Redistributable Package (x64) 

### ISSUE THREAD

**Issue by gruselglatz** [crate/crate#10516]
**CrateDB version**:
4.2.3

**Environment description**:
Windows Server 2019 10.0.17763-r1809

**Problem description**:

Crate can't Start without  Microsoft Visual C++ 2010 Redistributable Package (x64). And it has to be 2010 we tested every version.

I don't have any logs, but it's some problem with JNI.

**Solution**
Install  Microsoft Visual C++ 2010 Redistributable Package (x64) .

Pls Document it.

**Comment by amotl** [comment]
Dear @gruselglatz,

while doing some related work (see #10737), I have been able to verify CrateDB 4.3.1 successfully starts on Windows 10.0.17763 without further ado. For doing that, I used the "MSEdge on Win10 (x64) Stable 1809" image from [1] and started it within VirtualBox.

While I can't say for sure that this does not contain the _Microsoft Visual C++ 2010 Redistributable Package (x64)_, I still believe it is a very minimal Windows installation I have been using there.

So, I am humbly asking if you could verify the installation again using the most recent version from the downloads page [2] and report back to us? Any information how you have been able to run into this problem and respective logs would be helpful for us in order to investigate further. Thanks already!

With kind regards,
Andreas.

[1] https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
[2] https://cdn.crate.io/downloads/releases/cratedb/x64_windows/

**Comment by gruselglatz** [comment]
@amotl Yeah we can run it on Windows 10 without further installation of Visual C++ but on windows Server we need to install it manually. Our Admin said, under Windows Server there is no default installation of Microsoft Visual C++ 2010 Redistributable Package (x64).

**Comment by amotl** [comment]
Dear Herbert,

thanks for your quick reply. I understand. So, it is really a documentation issue for us. Thanks again!

Saying this, we might want to see whether #10738 will improve things in the regard to be able to use a more recent version of the _Microsoft Visual C++ Redistributable Package (x64)_ [1] and not having to install the ancient 2010 release [2].

If you are feeling lucky, you might want to ask your Admin to check whether it will work by manually replacing the `jna-4.2.2.jar` by `jna-5.6.0.jar` [3] within CrateDB's `lib` folder. Otherwise, we can just wait for the next minor release of CrateDB (probably 4.3.2) in order to get back to this detail before updating the documentation accordingly.

With kind regards,
Andreas.

[1] https://www.itechtics.com/microsoft-visual-c-redistributable-versions-direct-download-links/
[2] https://www.microsoft.com/en-pk/download/details.aspx?id=8328
[3] https://download.jar-download.com/cache_jars/net.java.dev.jna/jna/5.6.0/jar_files.zip

**Comment by gruselglatz** [comment]
@amotl We will test it, but not this week anymore, sry, i will come back to you next week. :)

**Comment by gruselglatz** [comment]
@amotl Sry for the late response, but I've tested it now. Only in Combination with the jna-5.6.0.jar i can start Crate with the latest 2019 Microsoft Visual C++ Redistributable Package (x64).

**Comment by mechanomi** [comment]
@amotl @gruselglatz I am looking at this issue again with a view to closing it out. as far as I understand it, with the changes made recently, I believe that the proper fix is to add a note to our docs saying that if you are installing on Windows Server Edition you must install Microsoft Visual C++ 2010 Redistributable Package (x64) as a dependency. (also, that the latest version of this will work). do I have the correct understanding?

**Comment by amotl** [comment]
Hi again,

thanks for getting back to this @gruselglatz and @mechanomi. The most recent releases of CrateDB 4.3.4 and CrateDB 4.4.0 both include the updated `jna-5.6.0.jar`.

If this was the right choice, CrateDB will start on recent versions of Windows without any warnings - even without having to install any MSVCRT package.

Can I humbly ask you to confirm this, @gruselglatz?

With kind regards,
Andreas.

---

```sh
wget https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.3.4.zip
wget https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.4.0.zip

unzip -l crate-4.3.4.zip | grep jna
  1509440  11-05-2020 00:03   crate-4.3.4/lib/jna-5.6.0.jar

unzip -l crate-4.4.0.zip | grep jna
  1509440  11-05-2020 00:03   crate-4.4.0/lib/jna-5.6.0.jar
```

**Comment by gruselglatz** [comment]
@amotl I tried it, and its starting without errors. Thanks for the fix. 👍
