### ISSUE TITLE
Memory leak with command INSERT

### ISSUE THREAD

**Issue by dla68** [crate/crate#10538]
**Crate version:** 4.2.4

**System:** Intel Core i7-8550U 1.80GHz 1.99GHz, 32GB RAM,  Windows 10 Pro V1903

**How to reproduce the error:**

When I create the table:

`CREATE TABLE memleak(plctime bigint,partid GENERATED ALWAYS AS (plctime / 30000),
val0 array(real) INDEX OFF,val1 array(real) INDEX OFF,val2 array(real) INDEX OFF,val3 array(real) INDEX OFF,val4 array(real) INDEX OFF,val5 array(real) INDEX OFF,val6 array(real) INDEX OFF,val7 array(real) INDEX OFF,val8 array(real) INDEX OFF,val9 array(real) INDEX OFF,
val10 array(real) INDEX OFF,val11 array(real) INDEX OFF,val12 array(real) INDEX OFF,val13 array(real) INDEX OFF,val14 array(real) INDEX OFF,val15 array(real) INDEX OFF,val16 array(real) INDEX OFF,val17 array(real) INDEX OFF,val18 array(real) INDEX OFF,val19 array(real) INDEX OFF,
val20 array(real) INDEX OFF,val21 array(real) INDEX OFF,val22 array(real) INDEX OFF,val23 array(real) INDEX OFF,val24 array(real) INDEX OFF,val25 array(real) INDEX OFF,val26 array(real) INDEX OFF,val27 array(real) INDEX OFF,val28 array(real) INDEX OFF,val29 array(real) INDEX OFF,
val30 array(real) INDEX OFF,val31 array(real) INDEX OFF,val32 array(real) INDEX OFF,val33 array(real) INDEX OFF,val34 array(real) INDEX OFF,val35 array(real) INDEX OFF,val36 array(real) INDEX OFF,val37 array(real) INDEX OFF,val38 array(real) INDEX OFF,val39 array(real) INDEX OFF,
val40 array(real) INDEX OFF,val41 array(real) INDEX OFF,val42 array(real) INDEX OFF,val43 array(real) INDEX OFF,val44 array(real) INDEX OFF,val45 array(real) INDEX OFF,val46 array(real) INDEX OFF,val47 array(real) INDEX OFF,val48 array(real) INDEX OFF,val49 array(real) INDEX OFF,
val50 array(real) INDEX OFF,val51 array(real) INDEX OFF,val52 array(real) INDEX OFF,val53 array(real) INDEX OFF,val54 array(real) INDEX OFF,val55 array(real) INDEX OFF,val56 array(real) INDEX OFF,val57 array(real) INDEX OFF,val58 array(real) INDEX OFF,val59 array(real) INDEX OFF,
val60 array(real) INDEX OFF,val61 array(real) INDEX OFF,val62 array(real) INDEX OFF,val63 array(real) INDEX OFF,val64 array(real) INDEX OFF,val65 array(real) INDEX OFF,val66 array(real) INDEX OFF,val67 array(real) INDEX OFF,val68 array(real) INDEX OFF,val69 array(real) INDEX OFF,
val70 array(real) INDEX OFF,val71 array(real) INDEX OFF,val72 array(real) INDEX OFF,val73 array(real) INDEX OFF,val74 array(real) INDEX OFF,val75 array(real) INDEX OFF,val76 array(real) INDEX OFF,val77 array(real) INDEX OFF,val78 array(real) INDEX OFF,val79 array(real) INDEX OFF,
val80 array(real) INDEX OFF,val81 array(real) INDEX OFF,val82 array(real) INDEX OFF,val83 array(real) INDEX OFF,val84 array(real) INDEX OFF,val85 array(real) INDEX OFF,val86 array(real) INDEX OFF,val87 array(real) INDEX OFF,val88 array(real) INDEX OFF,val89 array(real) INDEX OFF,
val90 array(real) INDEX OFF,val91 array(real) INDEX OFF,val92 array(real) INDEX OFF,val93 array(real) INDEX OFF,val94 array(real) INDEX OFF,val95 array(real) INDEX OFF,val96 array(real) INDEX OFF,val97 array(real) INDEX OFF,val98 array(real) INDEX OFF,val99 array(real) INDEX OFF)
CLUSTERED BY (plctime) INTO 4 SHARDS PARTITIONED BY (partid) WITH ("translog.durability" = 'ASYNC');
`

in combination with the following Java program to insert records, then I get after about 3 hours Heap errors due to a memory leak:

`package de.koerber.vis.mod.hub;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;

public class MemoryLeak {
    private static PreparedStatement insertStmt;

    public static void main(String[] args) throws ClassNotFoundException, SQLException, InterruptedException {
        Class.forName("io.crate.client.jdbc.CrateDriver");
        Connection con = DriverManager.getConnection("jdbc:crate://127.0.0.1:5432/", "crate", "crate");

        // Create prepared command
        StringBuilder sqlCmd = new StringBuilder();
        sqlCmd.append("INSERT INTO memleak (plctime");

        for (int i = 0; i < 100; ++i) {
            sqlCmd.append(",val").append(i);
        }

        sqlCmd.append(") VALUES (? ");

        for (int i = 0; i < 100; ++i) {
            sqlCmd.append(",?");
        }

        sqlCmd.append(")");

        insertStmt = con.prepareStatement(sqlCmd.toString());

        // Create INSERT commands
        Random random = new Random();

        while (true) {
            insertStmt.setLong(1, System.currentTimeMillis());

            for (int i = 0; i < 100; ++i) {
                Float[] values = new Float[1000];

                for (int j = 0; j < 1000; ++j) {
                    values[j] = random.nextFloat();
                }

                insertStmt.setArray(2 + i, con.createArrayOf("float", values));
            }

            insertStmt.execute();
            Thread.sleep(500);
        }
    }
}
`
A further effect is that the count of threads increases continuously. On the screen shots you can see the increase of memory and threads and also the Heap related log messages.
![memleak1](https://user-images.githubusercontent.com/51264550/93251189-2703c380-f794-11ea-9b19-31dda8a64b0c.PNG)
![memleak2](https://user-images.githubusercontent.com/51264550/93251195-2834f080-f794-11ea-8523-33b9bd8dd46a.PNG)

**Comment by mfussenegger** [comment]
That the number of threads are increasing is normal to a certain degree. Not all thread pools are fixed size, some are scaling up to a certain degree.


In regards to the increase of HEAP usage. It looks like no full GC happened. It's normal that the HEAP usage increases over time. Usually you'd see some kind of sawtooth pattern.  [There is a blog post that elaborates on the topic a bit](https://crate.io/a/look-youre-monitoring-distributed-java-application/)


Besides the GC behavior, there are certain components in CrateDB that will be held in-memory as long as the node is running, and that amount can increase. For example the cluster state - including the table schemas and so on are held in memory. In your test scenario you're creating partitions - that also results in new structures that need to be held in memory.

**Comment by rbracko** [comment]
Hello Mr. Fussenegger,

my colleague, Mr. Lang (who put initial ticket here), delegated this job to me, to investigate the problem in details.

I have performed a number of tests, each time creating a table from the very start (meaning: before each test, I have re-installed Crate). First test was performed by creating a new partition every 10 seconds; then I gradually decreased the frequency of creating the partitions, to see how it affects the memory (heap). 
I have used jconsole tool to monitor the memory; at the same time, I controlled it by executing the query found in the article you mentioned.  

![image](https://user-images.githubusercontent.com/5370578/94368446-71fece80-00e4-11eb-8f93-acb491ca391e.png)

![image](https://user-images.githubusercontent.com/5370578/94368460-7dea9080-00e4-11eb-8eda-41063af9499a.png)

![image](https://user-images.githubusercontent.com/5370578/94368464-8347db00-00e4-11eb-831e-3b16f9eefd3e.png)

![image](https://user-images.githubusercontent.com/5370578/94368472-88a52580-00e4-11eb-96ac-21075c2bb268.png)

![image](https://user-images.githubusercontent.com/5370578/94368484-9064ca00-00e4-11eb-8fa5-e3749e218949.png)

In last test (5), which was conducted 48 hours, heap max wasn't reached but it's only matter of time - the trend is clearly visible.

In brief, here are the results:

![image](https://user-images.githubusercontent.com/5370578/94368501-9eb2e600-00e4-11eb-96f6-56bb46dc0489.png)

You can see that time until reaching heap max (1 GB) heavily depends on partitions-create frequency. 
You can also notice the saw-tooth pattern is becoming smaller and smaller because the garbage collector has step by step lesser memory which he can release. And also pressing the button “start GC” doesn’t help. And at the end we see an OutOfMemory exception.

You are kindly asked to investigate this problem since it's obvious that creating the partitions leads to memory heap overhead.
If it can help you, I can send you log data of all my tests.

**Comment by mfussenegger** [comment]
> You are kindly asked to investigate this problem since it's obvious that creating the partitions leads to memory heap overhead.

Yes, as mentioned certain parts of partitions are held in-memory. If you are going to continue increasing the amount of partitions continuously you'll run out of memory or otherwise have a lot of overhead because of the large amount of metadata in the cluster state.


Partitions have to be used with care. We typically recommend monthly or weekly partitions. Anything else and you usually end up with too many partitions.

You can read more about that in our [sharding guide](https://crate.io/docs/crate/howtos/en/latest/performance/sharding.html)

**Comment by dla68** [comment]
Hello Mr. Fussenegger,
Thank you for your feedback. Your link was not really helpful because that chapter describes the relationship between partition and shard only:
![image](https://user-images.githubusercontent.com/51264550/94491257-2d5c5b80-01e8-11eb-9114-77acda1c44ac.png)

The only hint which I found is that there is a check if there are more than 1000 partitions (https://crate.io/docs/crate/reference/en/4.2/admin/system-information.html#number-of-partitions). But we have our memory issue already with 400 partitions. About 2 years ago one of your colleague told us that a partition should not be bigger than about 5GB. On the other side our application shall record about 7TB during 6 month, so based on this 5GB limit we will get more than 1000 partitions.

Please can you describe some facts so that we can do a solid calculation: 
- estimated overhead for one parition concerning memory storage
- suggested maximum size for one partition
- is the memory consumption linear per partition?
- if we work with ringbuffer of 300 partition, do you expect further a continuous memory increase?

Or can you give us a proposal how we should structure our 7TB recording data. Because we don't have the time to test the Crate database over such a long time every help from your side is welcome in order to realize a spot landing.

**Comment by mfussenegger** [comment]
Not sure who gave you that information, but our guideline is usually 10GB to 50GB per shard, not per partition, one partition can contain many shards.

If in doubt I'd rather go higher on the limit, maybe even more than 50GB per shard if you'd otherwise reach more than 500 shards per node.


> estimated overhead for one parition concerning memory storage

It's hard to estimate, as it depends on number of columns and other factors

> suggested maximum size for one partition

See above, it is about the number of shards and shard size. The partitioning of course effects that, but the primary concern is about the shards.


> is the memory consumption linear per partition?

Mostly. A single shard can further be divided into multiple segments. Each segment has some overhead. But they're merged in the background if possible - though at a certain amount of data you'll have multiple segments all the time.

> if we work with ringbuffer of 300 partition, do you expect further a continuous memory increase?

If the number of shards is stable and the number of documents is stable, there shouldn't be any increase in base memory consumption. You'll still see fluctuations in the memory usage based on queries and the normal JVM/GC behavior.


> Or can you give us a proposal how we should structure our 7TB recording data.

We offer that kind of service for paying customers.

**Comment by dla68** [comment]
Hello Mr. Fussenegger,

all your answers are very valuable for us. Thank you very much. Can it be that all this facts are not part of your documentation or have we overlooked them.

Question: Our company pays a yearly fee to crate.io. Do you mean this kind of payment in order to get support?

**Comment by mfussenegger** [comment]
> Can it be that all this facts are not part of your documentation or have we overlooked them.

There are some gaps in the documentation. We're going to look into them at some point.

> Question: Our company pays a yearly fee to crate.io. Do you mean this kind of payment in order to get support?

Yes. If your company pays a yearly fee you should have a support contact to which you can reach out.
