### ISSUE TITLE
Use kahan summation algorithm for sum aggregation

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10543]
Currently sum aggregations on numeric columns of type REAL or DOUBLE PRECISION uses a straight forward [x + y operation (Double::sum)](https://github.com/crate/crate/blob/0f37bac7d72776656471cef834b21e389a9443c3/server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java#L77).

```sql
SELECT sum(real_column) FROM tbl
```

There would be the [Kahan summation algorithm](https://en.wikipedia.org/wiki/Kahan_summation_algorithm)  which could be implemented to significantly reduce the numeric error of the sum aggregation.

Elasticsearch contains a [implementation of kahan summation](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/metrics/CompensatedSum.java) which could be integrated into CrateDB.

**Comment by Wiewiogr** [comment]
Hi :)
I am not sure how i should tackle that issue, wheather I should implement it [here](https://github.com/crate/crate/blob/0f37bac7d72776656471cef834b21e389a9443c3/server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java#L77), as you suggested or in [SumDouble](https://github.com/crate/crate/blob/0f37bac7d72776656471cef834b21e389a9443c3/server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java#L229)? Or maybe in both places?

I was running SumAggregationTest::testDouble test and it turns out that both SumAggregation::reduce and SumDouble::apply is run (SumAggregation::reduce is first) during that test. I've also made an experiment i have altered result of SumAggregation::reduce and later SumDouble::apply and it turns out that both values are affecting the result of the test.

Any suggestions?

**Comment by mfussenegger** [comment]
Done via https://github.com/crate/crate/pull/10674

Thank you @Wiewiogr
