### ISSUE TITLE
Setting crate.yml parameter network.host prevents Crate of being started

### ISSUE THREAD

**Issue by ag-rbr** [crate/crate#10762]
**CrateDB version**: 4.2.4

**Environment description**: Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz OS: Windows 10 Pro / CentOS 7

**Problem description**:

**Windows**

Default Crate config is being used; only crate.yml parameter `network.host` is explicitly set (refers to local host's IP address). Attempt to start Crate ends with following error:
`ERROR: [1] bootstrap checks failed
[1]: initial heap size [268435456] not equal to maximum heap size [1073741824]; this can cause resize pauses and prevents mlockall from locking the entire heap`

If I add following lines to crate.bat:
`if "%CRATE_HEAP_SIZE%" == "" (`
`set CRATE_HEAP_SIZE=2g`
`)`

just before the statement:

`if NOT "%CRATE_HEAP_SIZE%" == "" (`
`set CRATE_MIN_MEM=%CRATE_HEAP_SIZE%`
`set CRATE_MAX_MEM=%CRATE_HEAP_SIZE%`
`)`

then the problem disappears.

**CentOS**

By using the same (default) config, and setting crate.yml parameter `network.host` to local host's IP address, attempt to start Crate (by the shell command `sudo systemctl start crate`) is successfull. There is no need to change crate.in.sh file.

**Comment by mfussenegger** [comment]
If you change `network.host` it assumes that you're using CrateDB for production and enforces some [Bootstrap Checks][1] to ensure CrateDB is suitably configured. One of them enforces that the max and min heap are set to the same value. Here is more information about the [memory configuration][2]

The behaviour you observed is kinda expected.


[1]: https://crate.io/docs/crate/howtos/en/latest/admin/bootstrap-checks.html
[2]: https://crate.io/docs/crate/howtos/en/latest/performance/memory.html

**Comment by amotl** [comment]
Dear @ag-rbr,

thanks for writing in and reporting this.

@mfussenegger: The sysinit/systemd default settings apparently configure `CRATE_HEAP_SIZE=512m` [1], that's why `systemctl start crate` was successful without further ado. Shouldn't the ad-hoc startup scripts `crate.sh` and `crate.bat` provide the same convenience?

Unless we provide a similar out-of-the-box convenience for Windows users looking at running CrateDB as a real Windows service, that might be the least thing we could do here.

Saying that, we might also want to apply that improvement to the `crate.sh` file as well - like
```
CRATE_HEAP_SIZE=${CRATE_HEAP_SIZE-512m}
```

With kind regards,
Andreas.

[1] https://github.com/crate/distribute/search?q=CRATE_HEAP_SIZE

**Comment by mfussenegger** [comment]
I think we might want to go the opposite route and change the defaults in the CentOS packages. 512M is rather low.


We need to balance between first use experience which should just work - but also need to ensure that people configure their nodes properly.

This is why CrateDB by default binds itself to localhost where it disables bootstrap checks and allows a "best effort" cluster bootstrapping with other nodes running locally. This allows users to try it easily.

Once the configuration is changed and CrateDB is bound to a public interface, the bootstrap checks are enforced and there needs to be a proper configuration for it to form a cluster. This is to ensure that some settings that absolutely should be changed in production are set up accordingly. The heap size is one of the properties that has a big impact on the performance, so it should always be set.

**Comment by ag-rbr** [comment]
Dear Mathias, 
Dear Andreas,

many thanks for your help!

Kind regards,
Robert Bračko

**Comment by amotl** [comment]
Dear Mathias,

thanks a bunch for the elaboration, specifically for all others reading here. Does our documentation reflect these details both well and concise enough?

> We need to balance between first use experience which should just work - but also need to ensure that people configure their nodes properly.

Sure, this is a very important detail.

After rereading the original post by @ag-rbr 
> Attempt to start Crate ends with following error.

and trying to start CrateDB on my own behalf by using the ad hoc scripts, I recognize that this is really just a warning message instead of an error. I misinterpreted the issue that the machinery wouldn't start using `crate.bat` on Windows at all, so sorry for the noise.

With kind regards,
Andreas.

P.S.

> I think we might want to go the opposite route and change the defaults in the CentOS packages. 512M is rather low.

I had the same impression when finding this. Shall we just go ahead and increase these numbers to 2048M within the sysinit/systemd scripts?
