### ISSUE TITLE
Latest nightly CrateDB will not start on MacOS

### ISSUE THREAD

**Issue by juanpardo** [crate/crate#10863]
Latest stable version works as expected on the very same environment.

I am getting the following error:
`$ /Users/juan/.cache/cr8/crates/crate-4.4.0-202012140003-15ff41d/bin/crate
/Users/juan/.cache/cr8/crates/crate-4.4.0-202012140003-15ff41d/bin/crate: line 129: /Users/juan/.cache/cr8/crates/crate-4.4.0-202012140003-15ff41d/jdk/Contents/Home/bin/java: No such file or directory`

**CrateDB version**:
crate-4.4.0-202012140003-15ff41d

**Environment description**:
- OSX
- Java is installed locally through sdk, tried with versions 11 and 15 (in case of any weird collision)
- Darwin Admins-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

**Problem description**:

**Steps to reproduce**:

**Comment by mkleen** [comment]
The latest-nightly does not contain the build for os x, there is only a linux version available, because it is soley used for testing/benchmarking and not suitable for production yet. However if you really want latest version i would suggest to checkout the git repo, either build the distribution locally or run it with gradle. See https://github.com/crate/crate/blob/master/devs/docs/basics.rst for all the details. Otherwise i would suggest to go the latest stable version.
