### ISSUE TITLE
Clarification on executemany query size limit

### ISSUE THREAD

**Issue by robd003** [crate/crate#10944]
**CrateDB version**: 4.3.2

**Problem description**:
I was wondering if there were any guidelines on batch size for executemany() calls. Is there an overall query size limit? Limit for the number of rows? Does the limit change if I'm executing the query via the HTTP API or the PostgreSQL wire protocol?

**Comment by mfussenegger** [comment]
We don't have any concrete guidelines.

For HTTP there is a max content length that defaults to 100MB. If you send a HTTP request that is above that, you'll get a 413 request entity too large error.

I think for the PostgreSQL wire protocol we currently have no limit in place.


An optimal batch size depends on your workload. More specifically your record size and the available heap / memory load on the cluster. If you have large individual records you'll want to use a lower batch size. For smaller records you can use a larger one.

We typically see values ranging from 500 to 5000 being used. At some point increasing the batch size further doesn't result in significant further performance improvement, and at some point may degrade the performance because of the memory requirements. 


I'm afraid you'll have to do some testing, if you want to find the sweet spot for your use-case.

**Comment by robd003** [comment]
Thanks for the quick reply @mfussenegger! I'll do some testing and report back with my record size and performance based on different batch sizes to help the rest of the community.
