### ISSUE TITLE
SqlAlchemy 1.3 Support for Apache Superset 1.0.1

### ISSUE THREAD

**Issue by exwhyz** [crate/crate#11072]
**CrateDB version**: 4.4.1

**Environment description**:
 - Kernel: Linux DESKTOPXXX 5.4.72-microsoft-standard-WSL2
 - Distribution: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Number of nodes: 1
 - Python 3.8.5
 - Apache Superset 1.0.1

**Problem description**:
Apache Superset version 1.0.1 has a hard dependency on SQLAlchemy version 1.3.x and since Crate does not support SQLAlchemy 1.3.x it is not possible to load the Crate SQLAlchemy driver. The instructions here (https://crate.io/a/cratedb-apache-superset/) no longer work as a result. The error message reported by Apache Superset when adding the database is: ERROR: Could not load database driver: crate

**Steps to reproduce**:
Following the steps here (https://crate.io/a/cratedb-apache-superset/) and using the latest 1.0.1 version of Apache Superset

**Comment by amotl** [comment]
Hi @exwhyz,

thanks for writing in. We are working on SQLAlchemy 1.4 support at https://github.com/crate/crate-python/pull/391, which is not released yet. SQLAlchemy 1.3 should be supported.

However, @Aymaru just contributed https://github.com/crate/crate-python/pull/395, which might be needed to support recent versions of Apache Superset or some specific features. We will look into that.

Ah, now I am seeing it. The documentation at [1] is explicitly telling people to use
```sh
pip install sqlalchemy==1.2.18
```

Let me also look into that.

With kind regards,
Andreas.

[1] https://crate.io/a/cratedb-apache-superset/

**Comment by amotl** [comment]
Hi again,

I can confirm that the documentation at [1] is completely outdated. Let me share a recipe which works for me until we have updated the blog post or created a new one.

Please note that I am using Docker here instead of the `bash -c "$(curl -L https://try.crate.io/)"` command. The command outlined below will spin up an ephemeral container, so it will not be able to store any data beyond its runtime. Please have a look at [2] how to use a persistent data directory.

So, here we go:
```sh
# Run CrateDB
docker run -it --rm --publish 4200:4200 --publish 5432:5432 crate/crate:nightly

# Create and activate Python virtualenv
python3 -m venv .venv
source .venv/bin/activate

# Install Apache Superset and CrateDB driver
pip install apache-superset crate[sqlalchemy]

# Initialize Superset database
superset db upgrade

# Setup environment
export FLASK_APP=superset

# Create admin user
flask fab create-admin

# Setup the default roles and permissions
superset init

# Run Superset
superset run -p 8080 --with-threads --reload --debugger

# Navigate to UI
open http://localhost:8080/
```

Then, you will be able to add CrateDB to the list of databases at http://localhost:8080/databaseview/list/, the database URI `crate://crate@127.0.0.1:4200` is correct.

Based on this recipe, I have been able to import a CSV file successfully (you have to enable the "Allow Data Upload" in the "Extra" tab of the database settings dialog beforehand). However, the process does not grok timestamps with time zones properly yet, that is probably made possible through the improvement https://github.com/crate/crate-python/pull/395 by @Aymaru. I will ping you about it as soon as we have released a new driver version.

Please let me know if this works for you.

With kind regards,
Andreas.

[1] https://crate.io/a/cratedb-apache-superset/
[2] https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html#persistent-data-directory

**Comment by exwhyz** [comment]
Hi @amotl

I can confirm that after I install crate with SQLAlchemy support I am able to load the driver, upload CSV and explore the data. So the trick was to install crate using:

`pip install crate[sqlalchemy]`

instead of just:

`pip install crate`

Thanks for the tip!
