### ISSUE TITLE
SQLParseException[Cannot convert input string: "Y-m-dTH:i:s" to biginteger]

### ISSUE THREAD

**Issue by l7s** [crate/crate#11264]
**CrateDB version**: 4.5.0

**Environment description**: Single Crate.io 4.5.0 node installed from [here](https://cdn.crate.io/downloads/releases/cratedb/x64_linux/crate-4.5.0.tar.gz) running on Debian 9 x64

**Problem description**:

Prior to upgrading to 4.5.0 we used to ingest data using `COPY table_name FROM 'file:///....' ` with `timestamp` column values saved in `.json` files in format `Y-m-dTH:i:s` (date T time) - this worked just fine in Crate.io 3.2.8. 

In Crate.io 4.5.0 `COPY table_name FROM 'file:///....` works fine, however an attempt to `SELECT...` results in error:

```
SQLParseException[Cannot convert input string: "Y-m-dTH:i:s" to biginteger]
```

**Steps to reproduce**:

1. In Crate.io 4.5.0 create table as below:
```
CREATE TABLE test_table (
    "id" string primary key,
    "name" string,
    "timestamp" timestamp
 );
```

2. Save file `/tmp/record.json` with data:
```
{"id":1,"name":"foo","timestamp":"2021-04-13T12:24:00"}
```

3. Run SQL:
```
COPY test_table FROM 'file:///tmp/record.json' WITH ( overwrite_duplicates = true )
```
This will complete OK and table will show `1 Records`

4. Run SQL:
`SELECT *  FROM test_table`

Expected result: data from `test_table` is returned

Actual result: an error is produced: `SQLParseException[Cannot convert input string: "2021-04-13T12:24:00" to biginteger]`

**Comment by mfussenegger** [comment]
`COPY` isn't doing data sanitization see https://github.com/crate/crate/issues/10186 and the [documented behavior](https://crate.io/docs/crate/reference/en/4.5/sql/statements/copy-from.html#type-casts-and-constraints):


> CrateDB does not check if the column’s data types match the types from the import file. It does not cast the types but will always import the data as in the source file. Furthermore CrateDB will only check for primary key duplicates but not for other Column Constraints like NOT NULL


So what happens is that the `timestamp` is imported literally as text instead of as `timestamp`, this then blows up at select time.

That this worked in 3.2.8 was kinda by accident - because some parts were more lenient, but I think even back then it would have been possible that it breaks with certain queries. Or you at least paid for implicit conversations at runtime, making queries slower than they should be.


You could instead use the `insert-json` sub-command from [cr8](https://github.com/mfussenegger/cr8#insert-json) to import the data. The ingest speed should be similar if you're only importing from a single file and it correctly converts the data to match the schema.

**Comment by l7s** [comment]
Thanks for clarification. If I wanted to keep using `COPY table_name FROM 'file:///....` can you let me know what is correct notation for `timestamp` value in `JSON` files?

**Comment by mfussenegger** [comment]
> If I wanted to keep using COPY table_name FROM 'file:///.... can you let me know what is correct notation for timestamp value in JSON files?

Number of milliseconds since 1970-01-01T00:00:00Z

In crash you can check with:

```
cr> select '2021-04-13T12:24:00'::timestamp as ts;
+---------------+
|            ts |
+---------------+
| 1618316640000 |
+---------------+
SELECT 1 row in set (0.004 sec)
```

**Comment by l7s** [comment]
All clear, closing this Issue now.
