### ISSUE TITLE
Allow non-superusers to run certain ALTER CLUSTER commands

### ISSUE THREAD

**Issue by proddata** [crate/crate#11283]
**Use case**:
As a Admin-user I want to also often want to run certain administrative commands, since often I can't directly connect to the host of CrateDB (e.g. as only ports 5432 / 4200 are accessible). Also e.g. `ALTER CLUSTER SWAP TABLE` is useful, I one would want to **simulate** a materialised view behaviour

```sql
CREATE TABLE m_view_new AS SELECT ...
INSERT INTO TABLE m_view SELECT ... FROM source
ALTER CLUSTER SWAP TABLE m_view_new to m_view;
DROP TABLE m_view_new;
```

Also `ALTER CLUSTER SWAP TABLE` would be useful anyway for normal users.

**Feature description**:

Allow the following commands for non-superusers with admin-rights `AL`:

```sql
ALTER CLUSTER SWAP TABLE source TO target [ WITH ( expr = expr [ , ... ] ) ]
ALTER CLUSTER REROUTE RETRY FAILED
ALTER CLUSTER GC DANGLING ARTIFACTS
```

other commands should still require super-user rights e.g. `decommission` as one would expect access to the hosts anyway

```sql
ALTER CLUSTER DECOMMISSION <nodeId | nodeName>
```

**Comment by mfussenegger** [comment]
:+1: 

> ALTER CLUSTER SWAP TABLE source TO target [ WITH ( expr = expr [ , ... ] ) ]

I think this could/should even work with a combination of DDL, and DQL.

**Comment by BaurzhanSakhariev** [comment]
@proddata, could you please elaborate, what does "user with admin rights" mean? There can be a user with some privileges, what subset of ALL makes the user an admin?

**Comment by proddata** [comment]
Any user with `AL` privileges (they are always on cluster level.

I think **crate** as super user has all privileges 🤔

@BaurzhanSakhariev

**Comment by BaurzhanSakhariev** [comment]
Thanks! It's clear now.

**Comment by BaurzhanSakhariev** [comment]
> 👍
> 
> > ALTER CLUSTER SWAP TABLE source TO target [ WITH ( expr = expr [ , ... ] ) ]
> 
> I think this could/should even work with a combination of DDL, and DQL.

@proddata, could you please share your thoughts on that? So, SWAP TABLE is allowed for users holding at least one of:

1. `AL`
2. combination of `DDL` **AND** `DQL`

right?

**Comment by proddata** [comment]
For consistency, I would think that only allow those `ALTER CLUSTER` operations to `AL` would be an option

If we include  `DML` and `DDL` on both the source and target table there would be 3 optons:

- superuser `crate`
- `AL`
- `DDL` and `DQL` on both tables

**Comment by BaurzhanSakhariev** [comment]
> For consistency, I would think that only allow those `ALTER CLUSTER` operations to `AL` 

+1 to only AL

@mfussenegger, does SWAP TABLES simply change table names so that whenever we refer to B after the swap it will just go to former A object? I couldn't find anything about columns/schema correspondence or validation so I don't think data migration is happening.

I'm asking it as I'm figuring out DDL/DQL/DML combination to accomplish SWAP - and the hardest case is where both tables exist. To really achieve effect of fully swapping objects, i.e make B look exactly like A and vice versa, one needs to drop redundant columns from B, add lacking columns from A into B (DDL on B) + DQL on A, DML on B. ==> even if we don't need create table B we still need DDL on B. Also, even if dropSource == false, still need DDL on A to add/remove columns from B

probably it really makes sense just to keep AL - yes, users with required D* privileges can accomplish that, but if I'm right about swap = absolute replacement than nobody would do it in such a tricky way with adding/removing columns and it's still something with different semantics, as it doesn't affect shards as swap table does and it's not about swapping object references in metadata (if I got semantics correctly)
