### ISSUE TITLE
IGNORE NULL option in window functions behaves incorrectly

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#11645]
### CrateDB version

4.7.0 -SNAPSHOT-d872104

### Steps to Reproduce

```sql
CREATE TABLE test (a integer);
INSERT INTO test (a) VALUES (1), (2), (3), (4), (5);
```

Given the following query with `LEAD RESPECT NULLS`:
```sql
SELECT a, LEAD(a) RESPECT NULLS OVER (ORDER BY a)
FROM test
ORDER BY a
```
returns:
```
+---+---------------------------------------------+
| a | lead(a) RESPECT NULLS OVER (ORDER BY a ASC) |
+---+---------------------------------------------+
| 1 |                                           2 |
| 2 |                                           3 |
| 3 |                                           4 |
| 4 |                                           5 |
| 5 |                                        NULL |
+---+---------------------------------------------+
```

The same query with `IGNORE NULLS`:
```sql
SELECT a, LEAD(a) IGNORE NULLS OVER (ORDER BY a)
FROM test
ORDER BY a
```
returns:
```
+---+--------------------------------------------+
| a | lead(a) IGNORE NULLS OVER (ORDER BY a ASC) |
+---+--------------------------------------------+
| 1 |                                          2 |
| 2 |                                       NULL |
| 3 |                                          4 |
| 4 |                                       NULL |
| 5 |                                       NULL |
+---+--------------------------------------------+
```

### Expected Result

The result set of both queries is identical.

### Actual Result

The result set differs, there are unexpected `null` values produced by `LEAD IGNORE NULLS`.

**Comment by proddata** [comment]
@jweberpm @jeeminso 
Is this considered a bug for 4.7.x?

**Comment by jeeminso** [comment]
Thanks a lot for testing it out and identifying a bug (introduced by #11532) . It looks like `ignore nulls` with `order by` breaks, that `SELECT a, LEAD(a) IGNORE NULLS OVER () FROM test ORDER BY a` still passes.

Below is what I overlooked in my implementation (from crateDB docs):
`If ORDER BY is supplied the window definition consists of a range of rows starting with the first row in the partition and ending with the current row, plus any subsequent rows that are equal to the current row, which are the current row’s peers.`

However, `lead` should not be bounded by window definitions, but rather make use of the entire partition.

So, the fix for the mentioned case is simple though, I think I should spend some time to search for more edge cases. Any suggestions would be grateful.
