### ISSUE TITLE
Upper year range when parsing TIMESTAMP literals is limited to four digits (year 9999)

### ISSUE THREAD

**Issue by amotl** [crate/crate#11688]
Hi there,

this is an observation discovered at https://github.com/crate/crate/pull/11631#discussion_r696975429 I wanted to share with you. It might be a regression introduced with CrateDB 4.x.

With kind regards,
Andreas.

### CrateDB version

`>=4.0.0`

### CrateDB setup information

```
docker run -it --rm --publish=4200:4200 --publish=5432:5432 crate/crate:4.6.2
```

### Steps to Reproduce

```
psql postgres://crate@localhost:5432/doc
```

### Expected Result

```
doc=> SELECT '10000-12-31T23:59:20.001Z'::TIMESTAMP;
 CAST('10000-12-31T23:59:20.001Z' AS timestamp)
-----------------------------------------------
 10000-12-31 23:59:20.001+00
```

### Actual Result

```
doc=> SELECT '10000-12-31T23:59:20.001Z'::TIMESTAMP;
ERROR:  Text '10000-12-31T23:59:20.001Z' could not be parsed at index 0
```

**Comment by mfussenegger** [comment]
The parser became a bit stricter and years outside of the 4 digit range require a plus:

```
cr> SELECT '+292278993-12-31T23:59:59.999Z'::TIMESTAMP;
+-----------------------------+
| 9223372017129599999::bigint |
+-----------------------------+
|         9223372017129599999 |
+-----------------------------+
```

Given that this was discovered while working on the docs, and not due to a user application breaking, I'd tend to keep the new behavior. It made it through 5 more CrateDB versions and is the default parsing behavior of the java.time package.
(Switching the `DateTimeFormatter` to lenient would also have other implications, like accepting > 12 as month)

**Comment by amotl** [comment]
Hi Mathias,

thanks for sharing those insights. Given that PostgreSQL will not parse timestamps with years that large either, I also believe it is safe to keep it like you proposed. Let's keep this issue as a note for adjusting the documentation accordingly, right?

With kind regards,
Andreas.
