### ISSUE TITLE
Adding possibility to change setting on many/all tables at once

### ISSUE THREAD

**Issue by jayeff** [crate/crate#12154]
**Use case**:

For example after disk watermark flood stage is triggered potentially your tables will be put into read-only allow-delete. Once you have freed or added additional disk space you need to indivdually set `blocks.read_only_allow_delete=false` on every table.

In case you have many tables this could be a bit cumbersome. It would make this task simpler if I could run a single query to reset the setting for all tables at once.

Potentially (not to complicated) workaround: Have a script which loops over all tables and execute the SQL query for all of them.

**Comment by mfussenegger** [comment]
As far as I'm aware, other DBs don't allow changing the setting of multiple tables at once and creating a script should be easy enough.
Rather than adding specialized update tables syntax I think a more general approach could be to open up some form of stored procedures/scripting support.

We recently also added some logic that should automatically remove the `read_only_allow_delete` block once enough disk space is available again. That should reduce the need to bulk update settings.

Closing this as too niche for now.
