### ISSUE TITLE
Ability to use `UNION` with implicitly cast-able values/columns without explicit cast

### ISSUE THREAD

**Issue by proddata** [crate/crate#12511]
**Use case**:
Schema retrieval on JDBC/ODBC (Progress) driver site

**Feature description**:
```sql
SELECT 1::INTEGER
UNION 
SELECT null
```

```sql
SELECT 1::regclass
UNION
SELECT 1::INTEGER
```

--- 

in 4.8 this leads to:
```
UnsupportedFeatureException[Corresponding output columns at position: 1 must be compatible for all parts of a UNION]
```

**Comment by seut** [comment]
Similar issue happen on 4.7.x with `UNION ALL`

```
SELECT 1::INTEGER
UNION ALL
SELECT null
```


-> `UnsupportedFeatureException[Corresponding output columns at position: 1 must be compatible for all parts of a UNION]`

**Comment by mfussenegger** [comment]
I'm not sure this is a bug. Sounds more like a feature to me and I'm not sure if we should extend UNION to allow implicit casts.
We currently allow implicit casts in many places and had the impression that it was a bit of a mistake and too lenient.

I think we can allow `NULL` literals because they are kind of a bottom value fitting any type, but other than that I'd tend to keep the current semantics.

**Comment by proddata** [comment]
> I'm not sure if we should extend UNION to allow implicit casts.

I wrote that really more in the sense of PG compatibility:
```sql
SELECT 1::INT8 as a UNION SELECT 2.01 as a                                                                             ;
  a   
------
    1
 2.01
(2 rows)
```

```sql
SELECT 1.0::FLOAT8 UNION SELECT 1::INTEGER;
 float8 
--------
      1
(1 row)
```
