### ISSUE TITLE
Support `INTERVAL` values as input for `extract(field from source)` 

### ISSUE THREAD

**Issue by proddata** [crate/crate#12995]
### Problem Statement

To calculate the difference between two `DATE` or `TIMESTAMP` values, one can use the `age(<timestamp>,<timestamp>)` function, which returns an `INTERVAL`. This is fine, if one can directly use the `INTERVAL`, however if one would want to calculate the difference in weeks, one can't extract that information from an `INTERVAL` further in CrateDB.

### Possible Solutions

Support also `INTERVAL` values as input for `extract(field from source)`  following PostgreSQL
https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT

e.g.
```sql
SELECT EXTRACT(DAY FROM INTERVAL '40 days 1 minute');
Result: 40
```

### Considered Alternatives

```sql
-- calculating difference in months between two dates
SELECT
('2022-10-21'::DATE - '2021-08-21'::DATE)::BIGINT
    / (1000*60*60*24*30.5::NUMERIC);
```

**Comment by octocat999** [comment]
Support boostspeed 'ALL INTERVALLS'

**Comment by BaurzhanSakhariev** [comment]
Since weeks is mentioned as example use case:

CrateDB:  `SELECT 'P10D'::interval` returns  `1 weeks 3 days 00:00:00`

PG13: `SELECT 'P10D'::interval `returns `{"days":10}`

it's just representation in client but internal `Period` class has weeks field set to 3, and

`Period.days(10) != Period.weeks(1).days(3)` - so might affect streaming of that internal state(Period) to clients?

**Comment by matriv** [comment]
Imho, it's best if internally we return a Period with as fine grain info as possible, and then provide an `extract` variation with `INTERVAL` type to convert to what the user wants.
