### ISSUE TITLE
Equality match on empty arrays when using non-primitive inner-types IP, OBJECT, GEO_SHAPE, and BIT

### ISSUE THREAD

**Issue by amotl** [crate/crate#13105]
### CrateDB version

5.0.1

### CrateDB setup information

```
docker run --rm -it --publish=4200:4200 crate/crate:5.0.1 -Cdiscovery.type=single-node -Ccluster.routing.allocation.disk.threshold_enabled=false
```

### Steps to Reproduce

I am using the example program [`cratedb-empty-array-special-type.py`](https://gist.github.com/amotl/48f927570cb37787b656f7704cb538a7).

`python cratedb-empty-array-special-type.py equality` shows that the `WHERE details = []` check croaks on `ARRAY({IP,OBJECT,GEO_SHAPE,BIT})` column definitions.

### Expected Result

Not sure. `GEO_SHAPE` and `BIT` are listed as "Not yet implemented", so this will probably be fine. But `IP` and `OBJECT` raise an exception.

### Actual Result

- IP: `NullPointerException[Cannot invoke "org.apache.lucene.index.SortedSetDocValues.advanceExact(int)" because "docValues" is null]`
- OBJECT: `SQLParseException[Cannot search on field [details] since it is not indexed.]`
- GEO_SHAPE: `UnsupportedFeatureException[NYI: geo_shape]`
- BIT: `UnsupportedFeatureException[NYI: bit]`

**Comment by BaurzhanSakhariev** [comment]
On `ARRAY(OBJECT)` throwing `Cannot search on field [details] since it is not indexed`:

I think we need to use 
`if (ArrayType.unnest(dataType).id() != ObjectType.ID && ref.indexType() == IndexType.NONE) {`
instead of 
`if (dataType.id() != ObjectType.ID && ref.indexType() == IndexType.NONE) {`

in https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/expression/operator/EqOperator.java#L147

**Comment by amotl** [comment]
I can confirm the example program `cratedb-empty-array-special-type.py` produces the correct results when using the current `crate/crate:nightly` Docker image. Thanks a stack.
