### ISSUE TITLE
ALTER TABLE SET routing.allocation not working if a specific partition is not specified

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13299]
### CrateDB version

5.1.1

### CrateDB setup information

Number of nodes: 3

### Steps to Reproduce

1. Setup a 3 nodes cluster with a node called `crate-0`
2. ```create table testaltertable (partkey int,anotherfield TEXT) PARTITIONED BY (partkey) WITH (number_of_replicas=0)```
3. ```insert into testaltertable VALUES (1,'a'),(2,'b'),(3,'c')```
4. ```ALTER TABLE testaltertable SET ("routing.allocation.exclude._name" = 'crate-0');```
5. ```SELECT DISTINCT shards.node['name'] FROM sys.shards JOIN information_schema.table_partitions ON shards.partition_ident=table_partitions.partition_ident WHERE table_partitions.table_name='testaltertable'```

### Expected Result

No shards on `crate-0`

### Actual Result

The shards on crate-0 are not relocated.

Please note this works if the partitions are specified in the `ALTER TABLE` command:
```
ALTER TABLE doc.testaltertable PARTITION ("partkey"=1) SET ("routing.allocation.exclude._name" = 'crate-0');
ALTER TABLE doc.testaltertable PARTITION ("partkey"=2) SET ("routing.allocation.exclude._name" = 'crate-0');
ALTER TABLE doc.testaltertable PARTITION ("partkey"=3) SET ("routing.allocation.exclude._name" = 'crate-0');
```

I confirmed new partitions apply the setting, same as if we would have run `ALTER TABLE ONLY`

I can reproduce this consistently for `routing.allocation` settings, but other settings visible on `table_partitions` are changed for all partitions, ```ALTER TABLE testaltertable  SET ("mapping.total_fields.limit" = '7');``` for instance.

**Comment by jeeminso** [comment]
Had a quick look to see if this is related to #13295. 
#13295 is caused by having or not having `index.` in front of `number_of_replicas`, so unrelated.

For this one, I can see that 
`ALTER TABLE testaltertable SET ("routing.allocation.exclude._name" = 'crate-0')`
and
`ALTER TABLE doc.testaltertable PARTITION ("partkey"=1) SET ("routing.allocation.exclude._name" = 'crate-0');`
both properly carries
`{"index.routing.allocation.exclude._name":"crate-0"}`
up to `AlterTableClusterStateExecutor#execute`.

**Comment by jeeminso** [comment]
Had a look at this to check if this is related to #13295.
The cause is similar but the fixes should not overlap.

It looks to me that when the partition is not specified, the execution path reaches:
https://github.com/crate/crate/blob/27201a99bd320a831adf670dc44227c9c2967ca1/server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java#L145
And inside `filterSettings(...)`, `routing.allocation.exclude._name` is filtered because currently we only recognize `routing.allocation.exclude` as supported.
Maybe we should not simplify `Setting.AffixSetting<String> INDEX_ROUTING_EXCLUDE_GROUP_SETTING` to a `String`, losing the information that it is an `AffixSetting`.
