### ISSUE TITLE
Decrease COPY ... FROM bulk import time

### ISSUE THREAD

**Issue by bhaskarb2014** [crate/crate#1339]
In a particular use case, I am importing a single text file with approximately 78000 rows, with the size of the file being 797M.

I have done a number of runs and COPY ... FROM takes about approximately 105-110 seconds (best result).

Setup Details

(1) I am running a single node Crate with 5 shards on Intel(R) Xeon(R) CPU E5-2651 v2 @ 1.80GHz box with 7.5 GB memory.
(2) The environment variable CRATE_HEAP_SIZE is set to 4g.
(3) The table has a single column called 'data' whose value is a JSON object that contains 184 child objects.  Each one of these 184 child objects, in turn, has a minimum of 1 element and can have maximum of 2 elements.

The SQL script that I am using to insert data is given below:

DROP TABLE dummy;
CREATE TABLE dummy (data object) WITH (number_of_replicas = 0, refresh_interv
al = 0);
COPY dummy FROM 'file:///data/scripts/out/dummy/file-0'
 WITH (bulk_size=20);

I played with different bulk sizes and the best result I get is with a bulk size value of 20 (which may or may not be a good final value, I am just reporting my findings).

For this use case as per the requirements, the amount of time it is taking (~ 105s), is not acceptable.

I would be glad to listen to any hints/suggestions on ways to further decrease the bulk import time.

**Comment by wilkejj** [comment]
I am doing a proof of concept for work and using crate - and it looks very cool , however I to am having issues loading data in a timely fashion.  I've let the import go for days - and never completed the load.

I am loading (I think) in the neighborhood of 800 million records from JSON format in a gzipped file.

I have 3 hosts, with 3 nodes each - 9 nodes total.  I've experimented with multiple shard counts from the default of 5, up to 36.

My schema is:

create table order_plan (productId string
                                       ,locationId string
                                       ,runCycleDt timestamp
                                       ,referenceDate timestamp
                                       ,periodType string
                                       ,dateOffset double
                                       ,targetInventory double
                                       ,salesForecast double
                                       ,forecastedInventory double
                                       ,inventoryLastPeriod double
                                       ,demandForecast double
                                       ,demandObserved double
                                       ,salesObserved double
                                       ,fixedReceipts double
                                      ) CLUSTERED INTO 36 shards
                                      WITH (number_of_replicas = 0,
											refresh_interval = 0);

And I'm loading with:

copy order_plan from '/mnt/oradata/OP_DAILY_JSON_Extract_20141231_025133.CSV.gz' WITH (compression = 'gzip');

My machines have 8 CPU with 24GB of RAM each - along with SSD drives.

My data looks like:
{"productid" : "738527-110", "locationid" : "DIV|03", "runcycledt" : "2014-11-25", "referencedate" : "2014-11-25", "periodtype" : "DAILY", "targetinventory" : "43.831455", "salesforecast" : "0.5722885", "forecastedinventory" : "62.0", "inventorylastperiod" : "0.0", "demandforecast" : "0.59201336", "demandobserved" : "0.0", "salesobserved" : "0.0", "fixedreceipts" : "0.0", "dateoffset" : "0"}

What is a ballpark run time you would expect this data to load given the hardware I have.

Via nmon - there looks like a fair amount of CPU activity - but with 3 nodes per host - maybe that is expected.

Any tips you may have to speed up the load would be greatly appreciated

![screen shot 2015-01-08 at 9 04 34 pm](https://cloud.githubusercontent.com/assets/10458236/5674991/00f52290-977a-11e4-82f3-838e11c15ba4.png)

**Comment by wilkejj** [comment]
The attempt to load it tonight actually bombed out with:

cr> copy order_plan from '/mnt/oradata/OP_DAILY_JSON_Extract_20141231_025133.CSV.gz' WITH (compression = 'gzip');
SQLActionException[[order_plan][26] [1] shardIt, [0] active : Timeout waiting for [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@15af3544]

**Comment by dobe** [comment]
hi @wilkejj 

giving an estimate on what the performance should be is hard. however i think it should be possible to do around 50k records per sec, which means an import time of about 4-8 hours.

some questions:

- which version of crate and which OS are you on?
- ist ``/mnt/oradata`` a local disk or is it some kind of remote fs?
- the cpu usage comes from the indexing, make sure to only enable indexing on columns you really need indexed.

some suggestions:

- stick with one node per host, since this will be more efficient
- you have a lot of records. split the file into around 30 parts and distribute the parts across your nodes, this will also make it possible to split up the import command into more shorter executions by defining a pattern for the filename. if you have just one file, the bottleneck is probably the disk where the file resides. however for your schema and your amount of data it is normal that the cpu usage is that high upon import.
- dunno your heap size, but try to give crate half of your ram, and let the rest be used for FS cache.
- i suggest using 48 shards for your schema ( a little more than one shard per core)
- i think you already read https://crate.io/docs/stable/best_practice/data_import.html right?
