### ISSUE TITLE
Nested JOIN leads to IllegalStateException: joinPairs contains duplicate 

### ISSUE THREAD

**Issue by proddata** [crate/crate#13503]
### CrateDB version

5.1.3 / master

### Problem description

Not entirely sure if this is a 🐛 or just unsupported.
Came up in https://github.com/crate/cratedb-examples/pull/10#issuecomment-1398655879

### Steps to Reproduce

```sql
CREATE TABLE j1 (x INT);                                                    
CREATE TABLE j2 (x INT);                                                    
CREATE TABLE j3 (x INT);
                                                    
cr> SELECT * 
    FROM j1 
    JOIN (j2 JOIN j3 ON j2.x = j3.x) 
    ON j1.x = j2.x;                                                             
IllegalStateException[joinPairs contains duplicate: Join{INNER doc.j2 ⇔ doc.j3} matches Join{INNER doc.j2 ⇔ doc.j3}]
```

### Actual Result

```
IllegalStateException[joinPairs contains duplicate: Join{INNER doc.j2 ⇔ doc.j3} matches Join{INNER doc.j2 ⇔ doc.j3}]
```

### Expected Result

```
 x | x | x 
---+---+---
(0 rows)
```

**Comment by BaurzhanSakhariev** [comment]
Even non-nested JOIN fails and returns an empty result set in PG 15:

`SELECT * from j2 JOIN j3 ON (j2.x = j3.x and j2.x = j3.x)`

Of course it's a non-realistic query but I think we need to drop this duplicate pair check.

**Comment by BaurzhanSakhariev** [comment]
Thx for reporting the issue! The fix is being prepared in https://github.com/crate/crate/pull/13577.

There is another scenario which is affected by this issue (query doesn't fail and returns correct results but could have some incorrect internal optimizer hints). This will be also addressed by the same fix.

```
select * from j1
join j2 on j1.z = j2.x 
join j3 on j1.x = j3.x
```

**Comment by BaurzhanSakhariev** [comment]
Another issue with almost same query
```
SELECT * 
    FROM j1 
    JOIN (j2 JOIN j3 ON j2.x = j3.x) 
    USING(x);  --> ON is replaced by this
```
In PG 14 we get a good message `"common column name "x" appears more than once in right table"`
in CrateDB we get an error  
`ERROR: Cannot invoke "io.crate.analyze.relations.AnalyzedRelation.relationName()" because "rightRel" is null`

i.e error should happen but error message has to be improved.
