### ISSUE TITLE
Allow any characters in quoted names for schemas or tables

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#13586]
### Problem Statement

originally from: https://github.com/crate/crate/pull/13528#issuecomment-1406215556

> allow any characters inside quoted(delimited) identifiers beside double quotes itself as also allowed by other databases e.g. PG https://www.postgresql.org/docs/8.1/sql-syntax.html#SQL-SYNTAX-IDENTIFIERS and somehow a loose described at the SQL standard (e.g. https://crate.io/docs/sql-99/en/latest/chapters/02.html#delimited-identifier).

**Comment by DHRUV6029** [comment]
hi , can i take up this issue i have contributed 2 times to this repo already

**Comment by BaurzhanSakhariev** [comment]
Hi @DHRUV6029, thanks for your interest.

I have already assigned https://github.com/crate/crate/issues/2036 to you (because I saw your comment there before I saw this comment), let's tackle issues one by one. 

You can take this one of you want - feel free to unassign yourself from another issue then.

**Comment by DHRUV6029** [comment]
Hi I would take up another issue #2036 first , you can assign this one to somebody
