### ISSUE TITLE
copy from/to local blob storage

### ISSUE THREAD

**Issue by hofline** [crate/crate#1378]
Is posible import/export data from/to crate local blob storage?

Regards.
##

**Comment by jeteon** [comment]
I've run into this issue too. I ended up writing a utility script to dump the data and import it back in again. Basically, with some batch size (I use 100) and a break in between (I use 1s) it: 

  1. selects from the digests in the blob table with the appropriate offset and limits
  2. downloads each one using the blob API (these can be done in parallel so it doesn't take long)

You don't have to worry about names or anything since only the `sha1` matters in the blob tables. The import is really just step 2 in reverse, also batched to limit load.
