### ISSUE TITLE
`CREATE REPOSITORY`: Support Google Cloud Platform

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13879]
### Problem Statement

Google Cloud Platform users would like to use [Cloud Storage](https://cloud.google.com/storage/docs) as a snapshot repository, so snapshots can easily be stored on the Google Cloud Platform.

### Possible Solutions

Support Cloud Storage in `CREATE REPOSITORY`, similarly to how S3 and Blob Storage are supported.

---

@proddata: This could probably be realised by porting https://github.com/crate/elasticsearch/tree/master/plugins/repository-gcs over and updating it (if necessary)

**Comment by proddata** [comment]
Doesn't GCP offer an s3 compatible api as well?

**Comment by proddata** [comment]
Afaik the S3 version is at least also tested with MinIO, but probably could be documented better.
Probably we could also test some S3 alternatives like Backblaze B2 / Cloudflare R2 / etc.

**Comment by seut** [comment]
> Probably we could also test some S3 alternatives like Backblaze B2 / Cloudflare R2 / etc.

I do not see any reason to test various S3 compatible backends. This would test the S3 compatibility or these backends and not our code. If they claim to be S3 compatible, than any S3 client should work. It's not up to us to ensure this.

**Comment by amotl** [comment]
I think s/tested/evaluated and documented/ is what we are aiming at here, right?

**Comment by hammerhead** [comment]
> I think s/tested/evaluated and documented/ is what we are aiming at here, right?

Yes. Even if GCP turns out to be 100% S3 compatible, I think the main three cloud providers deserve high visibility in the documentation of core features like `CREATE REPOSITORY`/`COPY TO`/`COPY FROM`, even if it's just mentioning to use other parameters.
For other, less prominent, S3-compatible storage providers I would instead tend towards a community tutorial.

**Comment by seut** [comment]
I've just did a short test with using the `s3` repository type against GCS and I can validate that it doesn't work. 
The issue @petervrs described can be fixed by enabling ACLs on the bucket, see also https://cloud.google.com/storage/docs/aws-simple-migration#accesscontrol-simple.
But afterwards it still fails, after debugging the response of GCS, main problem is a slightly difference on the S3 compatibility of GCS, compared to AWS: they do not allow deleting multiple blobs via on API request which the `s3` repository implementation is using, see also https://github.com/s3tools/s3cmd/issues/.
I don't see a way to work around this with the `s3` implementation, such we probably need to add dedicated support for GSC.

**Comment by petervrs** [comment]
Thanks for the ACL suggestion @seut!

Can confirm my test fails with `RepositoryException[[] [test] cannot delete test data at [my-bucket-8]]` instead of `RepositoryVerificationException[[test] Unable to verify the repository, [test] is not accessible on master node` when I enable ACLs.

**Comment by bergwerf** [comment]
@seut We are considering developing a plugin that adds Google Cloud Storage as a possible repository. Do you have any suggestions on where to start and what to consider while figuring this out? So far I haven't found comprehensive documentation on how repositories work internally. The documentation I can find is some comments in the Java files that define the repository interface ([1]) and the existing S3 implementation ([2]). Right now the most viable approach seems to just copy the S3 implementation and substitute the AWS API with the GCS API.

[1]: https://github.com/crate/crate/blob/master/server/src/main/java/org/elasticsearch/repositories/Repository.java
[2]: https://github.com/crate/crate/tree/master/plugins/es-repository-s3

**Comment by seut** [comment]
@bergwerf 
Thank you for your interesting in contributing, this would be indeed very cool!
Unfortunately our plugin infrastructure isn't much documented and somehow hidden due to less interest in the past and such we did not improve it and the current state is a bit limited (related to what can be implemented by a plugin).
But for a repository plugin, the API is still there and working, as you already figured out, the [interface](https://github.com/crate/crate/blob/master/server/src/main/java/org/elasticsearch/plugins/RepositoryPlugin.java) and existing [S3 repository](https://github.com/crate/crate/tree/master/plugins/es-repository-s3) implementation are good starting points.

> Right now the most viable approach seems to just copy the S3 implementation and substitute the AWS API with the GCS API.

Yes I'd also suggest this.
Additionally, please have a look at the [Azure Repository plugin](https://github.com/crate/crate/tree/master/plugins/es-repository-azure), especially at the [plugin descriptor file](https://github.com/crate/crate/blob/master/plugins/es-repository-azure/src/main/resources/plugin-descriptor.properties) as this is really loaded via our plugin hooks, while the inclusion of the S3 (and URL) plugin is hardcoded into our [bootstrap code](https://github.com/crate/crate/blob/ed27d934225873a3360b2fc9e72658cd2b1417ff/app/src/main/java/org/elasticsearch/bootstrap/BootstrapProxy.java#L83).
Other than the plugin registration (and it's component) via the plugin interface and descriptor file, you would need to implement at least the [BlobStore](https://github.com/crate/crate/blob/ed27d934225873a3360b2fc9e72658cd2b1417ff/server/src/main/java/org/elasticsearch/common/blobstore/BlobStore.java) and [BlobContainer](https://github.com/crate/crate/blob/ed27d934225873a3360b2fc9e72658cd2b1417ff/server/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java) interfaces.

I hope this will help you in the first run to work on a draft. Once you have something maybe it's best to push a draft so we can support you then on concrete questions/issues.

**Comment by mkleen** [comment]
Resolved by https://github.com/crate/crate/pull/15517
