### ISSUE TITLE
Support custom class variables as session parameters

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#14359]
### Problem Statement

**Multi-tenancy scenario with one shared table**

Given a multi-tenant table that is implemented as `CREATE TABLE data (customer_id INTEGER, data INTEGER);`.
An application queries data from that table for specific tenants and does not want to use `SELECT * FROM data WHERE customer_id = x` due to concerns that the `WHERE` clause could be forgotten accidentally, exposing confidential data from all customers.

Approach (possible in PostgreSQL): Set the `customer_id` as a custom class variable and query through a view.

```sql
CREATE VIEW filtered_data AS
SELECT *
FROM data
WHERE customer_id = CURRENT_SETTING('myapplication.customer_id')::INTEGER;
```

Advantage of that view: It guarantees the filter is applied. If `myapplication.customer_id` is `NULL`, no data is returned.

The application can then query the view like this:
```sql
SET SESSION myapplication.customer_id = 1;

SELECT * FROM filtered_data;
```

### Possible Solutions

Support custom class variables: [Customized Options](https://www.postgresql.org/docs/15/runtime-config-custom.html)

### Considered Alternatives

Separate views for each user, permissions on specific views, use of `search_path` to point to the relevant views

**Comment by mfussenegger** [comment]
I'm not sure if this is a sound approach to deal with the described use-case.

`SET SESSION` can be run by any user, which means they could change their `customer_id` to that of a different customer.


Functions that operate on session state are also a bit problematic in CrateDB from an implementation perspective due to the distributed architecture. Functions can be executed in different contexts (handler node, or on the node holding the shards) and if we introduce custom session state we may need to serialize this across nodes all the time, without knowing for sure if it is needed.

**Comment by mfussenegger** [comment]
Closing this due to the reasos outlined in https://github.com/crate/crate/issues/14359#issuecomment-1778544567
