### ISSUE TITLE
Filtering by an empty object returns nothing

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#14457]
### CrateDB version

latest, 5.3.0

### Steps to Reproduce

```
cr> CREATE TABLE a (o OBJECT);                                                                                                                    
CREATE OK, 1 row affected  (0.298 sec)

cr> INSERT INTO a VALUES ({});                                                                                                                    
INSERT OK, 1 row affected  (0.009 sec)
```

### Actual Result

```
cr> SELECT * FROM a WHERE o = {};                                                                                                                 
+---+
| o |
+---+
+---+
```

### Expected Result

```
cr> SELECT * FROM a WHERE o = {};                                                                                                                 
+----+
| o  |
+----+
| {} |
+----+
```

**Comment by karenhernandeze** [comment]
Can I work in this?

**Comment by BaurzhanSakhariev** [comment]
Hi @karenhernandeze, sure, I assigned the issue to you. Thanks for your interest!

Just reflecting on the probably root cause: empty objects are not in the index and we have to do the full scan in such special cases. = are handled by `EqOperator` and for empty objects in should fall to genericFunctionFilter/full scan.

 [This](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/expression/operator/EqOperator.java#L135) would an entry point for investigations.

**Comment by BaurzhanSakhariev** [comment]
Hi @karenhernandeze, do you need help with this?
