### ISSUE TITLE
Embeddable Java Client

### ISSUE THREAD

**Issue by thesoulnerd** [crate/crate#1489]
For Java developers it would be nice if we could embed Crate Java Client directly into our Java Web application. With elasticsearch, this was possible and as far as I know the preferred way to do it.
##

**Comment by seut** [comment]
Did you maybe miss our java client jar package at bintray? https://bintray.com/crate/crate/crate-client/view (documentation: https://crate.io/docs/projects/crate-java/stable/)

**Comment by thesoulnerd** [comment]
I did, using it with Maven. Perhaps the description above is misleading. In elasticsearch it is possible to actually run an elasticsearch node within the same Java VM as the Web app providing an 'embedded client'. Would be nice to see that in Crate, too, though not a primary issue.

**Comment by seut** [comment]
Ah ok got it. Sorry no this is currently not supported but on our backlog. It could be already possible by including all related crate and depended jars but without any warranty (and support ;)

**Comment by chaudum** [comment]
Hi @thesoulnerd 
Some time passed since your request. We dropped the "native" Java client already some time ago in favour of JDBC which uses the Postgres wire protocol. This means that there is no "client" code any more to easily interface with the embedded CrateDB node, even embedding all jars in the project would theoretically work (did it?).
I want to close this issue, because the prerequisites to make this work are not there any more and CrateDB moved into a quite different direction within the last few years. Hope you understand. :)
