### ISSUE TITLE
Make it easier to identify what led to node crashes

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14938]
### Problem Statement

When a node crashes it is difficult to identify what was running at the time.
Configuring `stats.jobs_log_persistent_filter` results on statements being logged, but only once they complete.

### Open questions

- [ ] What about indirect load caused by participating in queries initiated from other nodes 
- [ ] How to prevent double logging and log spam
- [ ] Why is the heap dump that's generated on crash not enough? Via OQL it should be possible to find the statements that were running. Do we need docs/troubleshooting guides for that?

### Possible Solutions

Make so that `stats.jobs_log_persistent_filter` logs statements once they start if the expression does not include `ended` or `error` or introduce a new setting for this.

### Considered Alternatives

- A rolling network trace if ssl is not in use and the infrastructure setup allows for it
- Log statements from the client side if the clients are under our control
- Poll `sys.jobs` - maybe filtering only for queries that have already been running for longer than a given period of time (thanks @proddata )

**Comment by mfussenegger** [comment]
I don't think adding more logging is the way forward here.

- It would add additional overhead
- It's difficult to analyze, because you'd need to analyze if a query completed.
- With lots of requests/s there's a lot of data


CrateDB is also configured to create a heap dump on a crash. The heap dump contains the information of which queries had been active on the given node.

We could instead document how to analyze a heap dump. I think extracting the queries using OQL should be possible and is feasible to put into a how-to guide.


Another thing to consider is integration of something like OpenTelemetry, but afaik they usually take samples.

**Comment by hlcianfagna** [comment]
We have https://cratedb.com/docs/crate/howtos/en/latest/troubleshooting/docker-jcmd.html but this is particularly inconvenient in production container/Cloud environments.

**Comment by mfussenegger** [comment]
> We have https://cratedb.com/docs/crate/howtos/en/latest/troubleshooting/docker-jcmd.html but this is particularly inconvenient in production container/Cloud environments.

We could update the docs to give hints on how to configure the heap dump location so that it ends up in some network storage - or some other location that is more easily accessible.

In any case, logging is not the way forward to address this. A hprof file with a tool that supports OQL is a much better option to analyze ouf-of-memory crashes and requires no changes.

**Comment by BaurzhanSakhariev** [comment]
https://cratedb.com/docs/crate/reference/en/latest/config/environment.html says
>The directory to be used for heap dumps in the case of a crash.

However, looks like heap dump is captured only on OOM crash:
https://github.com/crate/crate/commit/8016cb2166cc380dbc0a6a3ba1eeb1d7cdb80bf2

Current master is the same: https://github.com/crate/crate/blob/master/app/src/main/dist/bin/crate#L170-L174

We observed a cluster crash caused by
`java.io.IOException: Map failed: MemorySegmentIndexInput`

and no heap dump was taken.

Not sure if it's possible to tweak JAVA_OPTS to capture a heap dump on any type of crash - I took a quick look, looks like not possible. 

With `systemd` one can use `OnFailure` hook, not sure about k8s clusters.

**Comment by mfussenegger** [comment]
> We observed a cluster crash caused by
> java.io.IOException: Map failed: MemorySegmentIndexInput
> and no heap dump was taken.

How would a heap dump help in that case?

**Comment by BaurzhanSakhariev** [comment]
> How would a heap dump help in that case?

We can see active queries, mmap-related-activity traces (snapshot, peer recovery). 

`MemorySegmentIndexInput` is one example, not-OOM crash not being captured is more general case, relates to https://github.com/crate/crate/issues/14938#issuecomment-1794439219

**Comment by hlcianfagna** [comment]
Please note also the original request was for tracing all requests before executing them, this would be resource intensive, we understand, but such a capture would give a very good chance of reproducing the problem replaying the very same steps a cluster went through when it ended up crashing.

**Comment by BaurzhanSakhariev** [comment]
We saw a crash related to direct buffer allocation.
`java.lang.OutOfMemoryError: Cannot reserve 4194304 bytes of direct buffer memory (allocated: 7515514463, limit: 7516192768)`

I wonder if we should apply `-XX:+HeapDumpOnOutOfMemoryError` to get a heap dump on any failure. While it won't help with direct buffer, it can at least give more insights about cluster state on the moment of the crash.

We could apply it on the STS for the particular cluster but I don't think this option will hurt if applied in general.

**Comment by amotl** [comment]
JFYI, that we made progress in this regard:

> We have https://cratedb.com/docs/crate/howtos/en/latest/troubleshooting/docker-jcmd.html but this is particularly inconvenient in production container/Cloud environments.

We provided additional tooling per [JFR collector](https://intra.cr8.net/docs/hemako/handbook/jfr/collector.html) subsystem in [Hemako](https://github.com/crate/hemako) to support production environments.
