### ISSUE TITLE
Support for aggregate function returning x most frequent values

### ISSUE THREAD

**Issue by proddata** [crate/crate#15000]
### Problem Statement

As a user I want to identify to most frequent values in a performant aggregation for a specified column. Approximations might be enough for large data sets.

e.g. to identify:
- the most frequent product IDs in a real-time sales transaction table.
- the most common error messages in a system log.

### Possible Solutions

Implement something similar to:
[TopK Aggregate function by ClickHouse ](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/topk)
returns the approximately most frequent values in a column
using [Finding top-k elements in data streams
](https://www.sciencedirect.com/science/article/abs/pii/S002002551000397X?via%3Dihub)

Or something like [approx_top_k](https://docs.databricks.com/en/sql/language-manual/functions/approx_top_k.html)

```sql
SELECT topK(3)(airline_id) FROM on_time
```

### Considered Alternatives

If performance would not be an issue, a correlated subquery / JOIN could be used.  Alternatively even a UDF

<details><summary>UDF Example</summary>
<p>

UDF
```sql
select 
country,
topk(array_agg(region),2)
from sys.summits
group by 1;
```

```sql
create or replace function topk(arr array(text), k int)
returns array(text)
language JAVASCRIPT
as
$$function topk(arr, k){
	const frequencyCount = {};
	for (let str of arr) {
		frequencyCount[str] = (frequencyCount[str] || 0) + 1;
	}
	const frequencyArray = Object.entries(frequencyCount);
	frequencyArray.sort((a, b) => b[1] - a[1]);
	return frequencyArray.slice(0, k).map(item => item[0]);
}$$
```
</p>
</details>

**Comment by hlcianfagna** [comment]
Another workaround:
```sql
WITH countries
AS (
	SELECT DISTINCT country
	FROM sys.summits
	)
SELECT country
	,array(	SELECT summits.region 
			FROM sys.summits 
			WHERE summits.country = countries.country 
			GROUP BY summits.region 
			ORDER BY count(*) DESC 
			LIMIT 2)
FROM countries;

```

**Comment by mfussenegger** [comment]
Or something like this?

```
select airline_id, count(*) from on_time group by 1 order by 2 desc limit 3;
```



`topK(3)(airline_id)` is probably not something we should do. We don't have functions as return types, but something like [approx_top_k](https://docs.databricks.com/en/sql/language-manual/functions/approx_top_k.html) could work with our existing framework


Given that this is supposedly motivated by performance:

- How many records are we talking about?
- What's the cardinality on the columns like?
- What's the current execution time using alternatives (like the group by)
- What would be an acceptable execution time?

**Comment by Tigraine** [comment]
Hi, since we just had an issue where this feature would have been helpful - is this still being considered - is this something we can expect to hit the product anytime soon?
We would really appreciate this feature as it unlocks a bunch of new customer features that currently require a lot of support effort to solve.

**Comment by mfussenegger** [comment]
>  is this still being considered - is this something we can expect to hit the product anytime soon?

I'd say some sort of solution for the top-k problem is definitely in scope for CrateDB.
It looks as if it is not making it into the 5.8 cycle where the current plan is to focus on disk space requirement reductions.

I've now bumped it up further for 5.9 so that it at least will pop up in discussions, but can't promise that it will stay there.

> This would be an alternative to groupBy not to the aggregation function.
Because one use-case we just ran into is that we'd have to get the score based on the HLL aggregation.
I can share more details in slack - but just counting is not enough but rather we want to replace groupBy to be resilient to high cardinalities. (can be solved by eg. https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch)

We recently added [DataSketches](https://datasketches.apache.org/) as dependency, and further exploring how we could use the probabilistic data structures it includes is on our TODO (but it's a long one..)
