### ISSUE TITLE
Performance regression for group by queries

### ISSUE THREAD

**Issue by piotrrzysko** [crate/crate#15133]
### CrateDB version

5.5.0

### CrateDB setup information

docker run -e CRATE_HEAP_SIZE=8g --publish 4200:4200 --publish 5432:5432 crate:5.5.0 -Cdiscovery.type=single-node

### Observed behavior

While exploring potential approaches to implement https://github.com/crate/crate/issues/13818, I noticed that since version 5.5.0, there is no significant difference in performance between the following two queries:

```
## Running Query:
   Statement:
     select count(distinct "cCode") from uservisits
   Concurrency: 15
   Iterations: 1000
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [04:20<00:00,  3.84 requests/s]
Runtime (in ms):
    mean:    3873.895 ± 25.701
    min/max: 1175.962 → 5471.169
Percentile:
    50:   3858.094 ± 414.655 (stdev)
    95:   4550.623
    99.9: 5451.031

## Running Query:
   Statement:
     select count("cCode") from (select "cCode" from uservisits group by "cCode") temp
   Concurrency: 15
   Iterations: 1000
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [04:09<00:00,  4.01 requests/s]
Runtime (in ms):
    mean:    3711.499 ± 33.076
    min/max: 610.013 → 6218.592
Percentile:
    50:   3673.261 ± 533.643 (stdev)
    95:   4679.652
    99.9: 6154.636
```

In version 5.4.5, the second query was significantly faster:
```
## Running Query:
   Statement:
     select count(distinct "cCode") from uservisits
   Concurrency: 15
   Iterations: 1000
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [04:22<00:00,  3.81 requests/s]
Runtime (in ms):
    mean:    3893.742 ± 22.845
    min/max: 966.737 → 5314.928
Percentile:
    50:   3894.481 ± 368.590 (stdev)
    95:   4456.188
    99.9: 5096.855

## Running Query:
   Statement:
     select count("cCode") from (select "cCode" from uservisits group by "cCode") temp
   Concurrency: 15
   Iterations: 1000
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:16<00:00, 60.13 requests/s]
Runtime (in ms):
    mean:    241.084 ± 3.909
    min/max: 108.970 → 780.635
Percentile:
    50:   239.353 ± 63.063 (stdev)
    95:   316.764
    99.9: 725.190
```

The flamegraphs captured during the execution of the above benchmarks for the query `select count("cCode") from (select "cCode" from uservisits group by "cCode") temp` suggest that in version 5.4.5, the GroupByOptimizedIterator was utilized.

5.4.5:
![image](https://github.com/crate/crate/assets/6481553/fe9c3c49-f651-49ab-aa88-679440d8178d)

5.5.0:
![image](https://github.com/crate/crate/assets/6481553/897ba990-6472-470c-aad8-5e685a541044)

After a brief investigation, I think the issue lies in these lines: https://github.com/crate/crate/blob/a2bfe918d8bcb44f0312b639f649ce10afbe0367/server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java#L135-L138 Currently, for the mentioned query, `keyFieldType` is always null. Consequently, the `GroupByOptimizedIterator` is never applied. This is because `keyRef.column().fqn()` evaluates to `cCode`, and the underlying map storing field types looks like this:
![image](https://github.com/crate/crate/assets/6481553/aac4c2c5-c790-4d83-9348-06474e9c8c90)
And used to look like this:
![image](https://github.com/crate/crate/assets/6481553/23767748-d68f-472d-a253-c1afe56636d7)

### Steps to Reproduce

Run this benchmark: https://github.com/piotrrzysko/crate-benchmarks/blob/eliminate_distinct/specs/distinct_eliminate.toml.

**Comment by piotrrzysko** [comment]
If this is not urgent, I can investigate the issue more thoroughly and try to fix it.

**Comment by BaurzhanSakhariev** [comment]
Hi @piotrrzysko, thanks for investigating this!

Yes, you are right, `MappedFieldType` lookup is a part of the problem.

A bit more context:

Since 5.5, each column has unique OID and data is stored in the source using OID-s as keys. 
This is done in order not to make column names part of data, so that we can drop columns.

As a consequence, all internal structures, which used to be registered by name, are now registered by OID (See https://github.com/crate/crate/commit/3a06c25db3daeee82d0f89df1d9b58495c5b19ba for details). For example, column stores, which are used for aggregations, also have to be accessed by OID instead of FQN. 

We need to  to use `Reference.storageIdent` instead of `Reference.column().fqn()` whenever we need column name to access some internal structure and use FQN only when we need human readable column name.


Looking further, I think https://github.com/crate/crate/blob/a2bfe918d8bcb44f0312b639f649ce10afbe0367/server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java#L145 is not a problem. FieldMappers are registered by OID, `name() `call should be safe there. 

However, https://github.com/crate/crate/blob/a2bfe918d8bcb44f0312b639f649ce10afbe0367/server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java#L184 could be also problematic. Could you please check it?

> I can investigate the issue more thoroughly and try to fix it.

Thanks! Performance regression is treated as a bug, so fix will be a part of the future 5.5.2 hotfix release.

**Comment by BaurzhanSakhariev** [comment]
I checked usages of `ColumnIdent.fqn()`, looks like https://github.com/crate/crate/blob/a2bfe918d8bcb44f0312b639f649ce10afbe0367/server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java#L115 might be also problematic.

**Comment by piotrrzysko** [comment]
Thanks for the reply. 



> Looking further, I think
> 
> https://github.com/crate/crate/blob/a2bfe918d8bcb44f0312b639f649ce10afbe0367/server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java#L145
> 
> is not a problem. FieldMappers are registered by OID, `name() `call should be safe there.

In the issue description, I was referring to the condition just above the one you pointed out :).

> However,
> 
> https://github.com/crate/crate/blob/a2bfe918d8bcb44f0312b639f649ce10afbe0367/server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java#L184
> 
> is most likely a problem. Could you please check it?

Yes, you are right, that was another place where `column().fqn())` was used incorrectly.

I submitted a PR that fixes the issue in all three places.
