### ISSUE TITLE
Reduce amount of memory required for running `ANALYZE`

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#15152]
### Problem Statement

Currently `ANALYZE` gets `30_000` samples per table per node. See:

- https://github.com/crate/crate/blob/df549946d1774f2539e0ce1e6b7ef1bc60dbf298/server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java#L85
- https://github.com/crate/crate/blob/df549946d1774f2539e0ce1e6b7ef1bc60dbf298/server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java#L242-L249

That can use up a lot of memory and result in high GC activity.

### Possible Solutions

We create table stats from these samples:

https://github.com/crate/crate/blob/df549946d1774f2539e0ce1e6b7ef1bc60dbf298/server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java#L194-L223

Maybe we could already compress the samples in the node-action in some form, ideally incrementally, to never materialize `30_000` records, and then merge the stats together.
E.g.
- hyperloglog could be re-used to calculate the distinct values
- [frequency sketch](https://datasketches.apache.org/docs/Frequency/FrequencySketchesOverview.html) for the most common values could be an option?

### Considered Alternatives

- Configure or auto-tune sampling size based on available heap/record size, but that reduces the quality of the stats.
- Suffer the GC
- Throw hardware at the problem

**Comment by JanaganSaravanan** [comment]
Hi! Is this issue still open ? If yes, Can you assign it to me ? And give small head start. Thank you,

**Comment by mfussenegger** [comment]
Yes it's still open, but for first contributions I suggest to start with something smaller. Look for the "good first issue" label.

**Comment by JanaganSaravanan** [comment]
Yep. Got it. Thank you for the suggestion.

**Comment by romseygeek** [comment]
There are plenty of things we can do here.  We should definitely explore using mergeable sketch datastructures to build the data in the first place, but the way the data is being loaded is fairly inefficient as well (eg a new docvalues or storedvalues reader is built for every document rather than being shared across segments), and there is some data such as minimum or maximum values that can be read directly from index data rather than sampling the dataset.

A useful first step would be to move the logic that converts a `Samples` instance to a `ColumnStats` instance directly into `Samples` itself; this would make `Samples` completely opaque to outside code and allow us to change its internal implementation.  We can then progressively update the collection code to improve efficiency or to use sketches while still being able to work in a mixed-version cluster.

**Comment by mfussenegger** [comment]
> , but the way the data is being loaded is fairly inefficient as well (eg a new docvalues or storedvalues reader is built for every document rather than being shared across segments

I attempted to change that a while ago, see https://github.com/crate/crate/pull/15078/files - but wasn't able to measure any actual improvement so I left it unchanged.

**Comment by romseygeek** [comment]
Oh that's interesting.  Maybe because the sampled docs are sufficiently spaced out that decoded blocks don't get re-used and we end up changing state on every lookup anyway?  If we move to using sketches then we might want to drop the sampling step altogether, but I think the logic would be sufficiently different then that most of this code would be replaced entirely.  So it's probably not worth exploring that as an intermediate step.

**Comment by romseygeek** [comment]
A brief outline of an implementation plan for this:
- [ ] Move all stats generation code into the `Samples` class to make it easy to change implementations (#15565)
- [ ] Replace `Object[]` arrays inside `Samples` with data sketches
- [ ] Change sampling logic from per-row loading to per-column
- [ ] Specialise column analysis where lucene metadata allows it (eg generate histogram from BKD tree, use term dictionary to get cardinality and high freq terms)
