### ISSUE TITLE
Performance regression for (group/hash) aggregates without doc-values

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#15224]
![image](https://github.com/crate/crate/assets/38700/8686623b-e5ee-4661-8b03-d374d5b897a6)

Ran a git bisect and it looks like the source parser changes for the OID are causing it:

```
git bisect run cr8 run-crate "$(pwd)" -e CRATE_HEAP_SIZE=4g \
    -- run-spec ~/dev/crate/crate-benchmarks/specs/select/disabled_doc_values.toml '{node.http_url}' \
        --re-name global_count_cCode \
        --fail-if '{runtime_stats.median} > 12000'

3a06c25db3daeee82d0f89df1d9b58495c5b19ba is the first bad commit
commit 3a06c25db3daeee82d0f89df1d9b58495c5b19ba
Author: Sebastian Utz <su@rtme.net>
Date:   Wed Sep 13 17:50:20 2023 +0200

    Store and read columns by their OID

    Use the column's OID inside the stored source and lucene fields
    instead of the columns name:
     - write the source map using the OID
     - use the OID as the Lucene field's name
     - lookup Lucene fieldmappers by the columns OID (be able to parse
       a raw document containing only OID's such as documents stored inside
       the translog)
     - lookup reference resolver by OID
     - convert the OID back to the columns name on reading objects/raw-doc
```

**Comment by piotrrzysko** [comment]
I've looked into this. Here are the flamegraphs captured while running the benchmark:

Commit 3a06c25db3daeee82d0f89df1d9b58495c5b19ba (slow):
![3a06c25db3daeee82d0f89df1d9b58495c5b19ba](https://github.com/crate/crate/assets/6481553/2f324965-0c74-46ec-92a8-832772290163)

Commit 67936ad09b7857dac1d74cae91d154f57a75169e (the commit preceding the one where the performance dropped):
![67936ad09b7857dac1d74cae91d154f57a75169e](https://github.com/crate/crate/assets/6481553/d5c045e3-4d13-4b94-a549-cbba35e6c4de)

This is what caught my attention:

The slower version:
![3a06c25db3daeee82d0f89df1d9b58495c5b19ba_nextToken](https://github.com/crate/crate/assets/6481553/0bc34292-0aba-4ebf-98e5-683df5220e8a)

The faster version: 
![67936ad09b7857dac1d74cae91d154f57a75169e_nextToken](https://github.com/crate/crate/assets/6481553/fc589d81-ed63-415a-a6f6-aad7a7f79e2f)

Jackson caches field names in `com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer`. If a field is stored in the cache, there is no need to execute expensive processing in `com.fasterxml.jackson.core.json.UTF8StreamJsonParser#addName`. The cache is synchronized in the `com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer#mergeChild` method, which collects names from different `ByteQuadsCanonicalizer` instances. The synchronization happens when the method `UTF8StreamJsonParser#close` is called.

It turns out that the instances of the parser used in `SourceParser#parse` were never closed, thereby the synchronization could not happen. However, a JSON containing column names (`cCode`, `sourceIP`, `destinationURL`, etc.) is parsed when indexes are created (`org.elasticsearch.indices.cluster.IndicesClusterStateService#createIndices`); this, in turn, populates the cache with the names (on this path, the parser is closed). After switching to OIDs, the cache is not populated with the corresponding field names (`1`, `2`, `3`, etc.).

I've prepared a fix: https://github.com/piotrrzysko/crate/commit/01237897f91a12eb28b612c026ddd24d2afdcd01. Below are the results:

Commit 3a06c25db3daeee82d0f89df1d9b58495c5b19ba (slow):

```
## Running Query:
   Statement:
     select count("cCode") from uservisits_no_doc_values
   Concurrency: 1
   Iterations: 50
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [12:38<00:00, 15.16s/ requests]
Runtime (in ms):
    mean:    15161.852 ± 264.240
    min/max: 13888.311 → 18091.129
Percentile:
    50:   15048.388 ± 953.296 (stdev)
    95:   16876.496
    99.9: 18091.129
```

Commit 67936ad09b7857dac1d74cae91d154f57a75169e (fast):

```
## Running Query:
   Statement:
     select count("cCode") from uservisits_no_doc_values
   Concurrency: 1
   Iterations: 50
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [09:56<00:00, 11.94s/ requests]
Runtime (in ms):
    mean:    11933.553 ± 62.089
    min/max: 11696.968 → 12979.255
Percentile:
    50:   11897.516 ± 223.996 (stdev)
    95:   12404.603
    99.9: 12979.255
```

Fix (https://github.com/piotrrzysko/crate/commit/01237897f91a12eb28b612c026ddd24d2afdcd01):

```
## Running Query:
   Statement:
     select count("cCode") from uservisits_no_doc_values
   Concurrency: 1
   Iterations: 50
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [10:04<00:00, 12.09s/ requests]
Runtime (in ms):
    mean:    12091.055 ± 70.764
    min/max: 11813.273 → 13304.890
Percentile:
    50:   12039.352 ± 255.294 (stdev)
    95:   12564.452
    99.9: 13304.890
```

It appears that the performance has improved after applying the fix. However, it is still slightly worse compared to the state before the switch to OIDs. I can delve deeper into this later this week.

**Comment by matriv** [comment]
thx a lot for your effort @piotrrzysko !
Also, Happy new Year!

It already looks good, and it would be great to dig deeper indeed, to see if further improvement can be made, thank you!!

**Comment by piotrrzysko** [comment]
Happy New Year to you too!

I've rerun the benchmark a few more times, and the results fluctuate around similar values. Sometimes, my version is faster, and at other times, the version before introducing OIDs is faster.

Additionally, I've microbenchmarked `io.crate.expression.reference.doc.lucene.SourceParser#parse`, and here the results are consistent - every time, the version from my branch is faster.

Would you like me to submit a PR with my changes and perhaps test it on your machine?

**Comment by mfussenegger** [comment]
Nice investigation. 

> Would you like me to submit a PR with my changes and perhaps test it on your machine?

yes please
