### ISSUE TITLE
Unexpected result when casting integer as boolean

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15537]
### CrateDB version

CrateDB 5.7.0-SNAPSHOT (built 6e7588d/NA, Linux 5.15.0-67-generic amd64, OpenJDK 64-Bit Server VM 21.0.2+13-LTS)

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the third query returns an empty result, because the second query returns `TRUE`, and the value of the `WHERE` predicate should be `TRUE`. If removing the PK constraint, the third query returns `2`, which is expected.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0(c0 INTEGER, PRIMARY KEY(c0)); -- PK is needed
INSERT INTO t0 (c0) VALUES (2);
REFRESH TABLE t0;

SELECT * FROM t0; -- 2
SELECT (CAST(t0.c0 AS BOOLEAN)= true) FROM t0; -- TRUE
SELECT * FROM t0 WHERE (CAST(t0.c0 AS BOOLEAN)= true);
-- Expected: 2
-- Actual: Empty Table
```

### Actual Result

As mentioned above

### Expected Result

As mentioned above

**Comment by matriv** [comment]
This is in the same context as: https://github.com/crate/crate/issues/15326
but a bit different, since now we have an explicit cast which the symbol optimizer cannot optimize, so we end up with executing a `Get` plan with `docKeys={true}` (a boolean value), but the `c0` column is an integer so we cannot match a boolean `true` for it.

The issue seems to me more complex, as we cannot simply do a symbol optimization and move the cast to the literal, `t0.c0 = (CAST true AS INTEGER)` , as the cast cannot give back `2` or any other integer that casts to boolean `true`.

**Comment by matriv** [comment]
Thx a lot @suyZhong for reporting this issue, it has been fixed and will be available with the next hotfix release.
