### ISSUE TITLE
Question: Parent/Children

### ISSUE THREAD

**Issue by mindbits** [crate/crate#1596]
Hi, 

having worked extensively with Elasticsearch before, I am a bit confused. Does the concept of Parent/Children not exist in Crate? 

M.

**Comment by spanktar** [comment]
Mindbits:

So, the short answer is no. Currently the team is working on SQL JOINs, starting with cross JOINs and that work is well underway, but we don't have a release date yet. You could enable the Elasticsearch API (disabled by default with Crate) and use the REST API to establish this relationship, but whether the relationship would hold through subsequent Crate SQL activity is unclear.  Crate keeps its table information in its own indexes that ES doesn't know about so things could get awkward, so this isn't recommended. That doesn't stop you from experimenting with it!

If you had data that you wanted to treat this way, one option is that you could create these indexes the traditional ES way and use the parent/child relationships. This data would essentially exist outside of Crate. The indexes will show up as tables in Crate but if you just ignore them, you could do it.

The other things to do, as recommended here, is to do this in your application logic, since even if you use parent/child the ES way, you'll still be taking a huge performance hit (the exact thing we're working to solve here):
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/parent-child-performance.html

and the recommended advice:
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/denormalization.html
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/application-joins.html

Crate is working full-tilt on JOINs and a lot of refactoring and optimizing is currently underway. Joins will always be expensive, especially when the sets are large and the data replicated and distributed.  Cross joins probably won't address your use case (what is your use case, actually?) but after cross joins we will move on to more common joins; cross joins are the foundation.

Does this help?

**Comment by mindbits** [comment]
Thanks for the indepth reply. 

looking forward to your cross joins then! :)

**Comment by mindbits** [comment]
oh, and the use case is eg

parent: invoice base data
children: the invoice positions

and then I want to aggregate on the customers , or the article codes or eg the invoice positions in relation to the city etc. 

but also the invoice positions need to be queried independently. this can all be done easily with parent/children in elasticsearch. 

could this be done with crate as well?

Also, I am a bit confused by "You could enable the Elasticsearch API (disabled by default with Crate)... This data would essentially exist outside of Crate." .. so it's possible to do a 'best of both worlds' approach in edge cases?

**Comment by mindbits** [comment]
an invoice is not the smartest example. 

parent: music example
children: different tracks
grandchildren: different qualities of the tracks

would this be possible with crate right now? I guess with application joins and when we store the parent ids in a _parentID field that we create manually it would, right?

**Comment by chaudum** [comment]
hi @mindbits 

your examples are not possible (yet) with crate, but as you said you can achieve it by doing multiple requests and join them on the application side.

concerning ES and Crate and "best of two worlds": Crate is using a (continuously updated) fork ES as a library, but that means that there are a few differences and ES may behave different than you think, see: https://crate.io/blog/crate_data_elasticsearch/ so it is definitely possible to use ES for edge case
