### ISSUE TITLE
Introduce a timeout for the Parsing/Analysis/Planning stage

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16071]
### Problem Statement

In an environment where users can run arbitrary queries, or where applications can be induced to run queries of increased complexity, it is desirable for administrators to be able to limit how many resources can go into individual requests to avoid that a few requests, accidentally or with malicious intent, prevent other request from performing adequately.

CrateDB already has a `statement_timeout` but it does not currently apply to optimization time.

Relates with https://github.com/crate/crate/issues/15997 and https://github.com/crate/crate/issues/16066

### Possible Solutions

- make the existing `statement_timeout` also apply to optimization time?
- introduce a separate "compilation" timeout as in other systems

**Comment by hlcianfagna** [comment]
If time were difficult to check maybe this could take the form of some other limit? (number of iterations or something like that)

**Comment by matriv** [comment]
1. A naive approach that we can backport would be to just add a count of how much time is spent on each step (parser, analyzer, planner) and check for every one of them if the timeout has expired before moving to the next, and finally the execute. Of course, in this case, we don't interrupt the statement, so we don't protect against lots of resources being used during those phases.
2. We need to pass the ScheduledExecutorService from the thread pool, to all those components, so that we can call schedule() with the timeout set, to have the same behavior as we currently have only for the execution phase.
    - We still need to count for the time spent in previous steps and subtract from the value we get from the setting.
    - We need to inject the scheduler into all those components, which requires some work, and also adjust our test layer accordingly.
    - Parser, analysis, planning (and optimizing) we all become async, unless you have some other idea to implement the interruption.

As discussed, we will go with the proper solution (2), as with the 1st one we don't address the issue of interrupting the statement and prevent it from continuing to consume resources.

**Comment by matriv** [comment]
Using just a separate thread and using the scheduler, won't solve the issue of being able to interrupt the execution at any point, as there needs to be a repeated check which evaluates the time passed against the timeout setting.

So, we just need to add checks for the time passed after Parser, after Analysis, and in a couple of places where we have iterations (check probably on every X iterations): EqualityExtractor (the iteration over the cartesian product) and plan Optimizer.
(Perhaps check if there is another similar code path that could potentially consume too much time).
