### ISSUE TITLE
(Inability to resolve) instability due to partition by high-cardinality field

### ISSUE THREAD

**Issue by devoncrouse** [crate/crate#1619]
Java 1.7.0_60
Crate 0.45.7

We're proving out some use-cases for potentially deploying Crate in production, and could use some guidance for properly configuring the cluster to prevent or contain problematic queries. Below is an example of us getting into some trouble, and not really knowing how to get out of it without interrupting the service.

1.	crash: create partitioned table called `tmessages_part` – partitioned by a high-cardinality field
2.	crash: insert into the partitioned table by selecting data from another large table
3.	Thousands of partitions created seemingly endlessly, cluster responses intermittently lagging as a result (UI timing out regularly, then returning to warning state due to unallocated partitions for new indices)
4.	“Ctrl-c” within crash in an attempt to kill the insert statement
5.	Background process(es) still continuing to create partitions/indices
6.	crash: `drop table tmessages_part;`
7.	Partitions continue to be created, though now without aliases as viewed through the Head plugin. Table and partition data now missing in information_schema.
8.	crash: `delete from tmessages_part` – didn’t do anything
9.	Let it run for a while (20-30 minutes) with a drop index loop against ES directly for cleanup, to see if it would "finish"
10.	Shut down the cluster
11.   On startup, lots of `[io.crate.metadata.shard.ShardReferenceResolver] Orphaned partition '[.partitioned.tmessages_part.0466it31ekn66rrd5ph74]' with missing table 'tmessages_part' found`
12.   Cluster status yellow and replicating, and number of shards/indices constant

**Comment by chaudum** [comment]
hi @devoncrouse 

we're sorry to hear about your problem!
the problem you are describing is due to the fact that you cannot abort a long running job yet once it has been dispatched, something that could also happen when you perform a large COPY FROM.
Using Ctrl-C in the crash does only interrupt the HTTP request, but does not cancel the job.
Unfortunately, right now, restarting the cluster - with all its problems - is the only way to cancel such a task. We've a feature in our backlog to tackle this problem!

however, I am a bit confused why you would use a table partitioned by a high-cardinality field. the opposite (low-cardinality) really is how you wanna use partitions.

I guess, what you want is to use the user column for routing: `CLUSTERED BY (user)` to improve performance of lookups by user. see: https://crate.io/docs/en/latest/sql/ddl.html#routing

hope I could help!

**Comment by devoncrouse** [comment]
I agree that the statement is misguided, but it's easy enough to do by accident; with the scale of data we're trying to index/store, we need to be able to contain something like that (in the same way we can kill MapReduce jobs through the JobTracker, for example), rather than forcing us to interrupt service and risk corrupting things. Hope to see some job control (or at least ACLs) in the future. Thanks!
