### ISSUE TITLE
Unexpected result when comparing `CHAR` with `''`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16689]
### CrateDB version

CrateDB 5.9.0-SNAPSHOT built 1064365

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the last query returns no row because the result of the second query is evaluated as `TRUE`. Or the second query is unexpectedly evaluated to `TRUE`. PostgreSQL returns `false` for the second query.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;

CREATE  TABLE  t0(c0 CHAR(3));
CREATE  TABLE  t1(c0 CHAR(3));
INSERT INTO t0(c0) VALUES (' ');
INSERT INTO t1(c0) VALUES ('a');
REFRESH TABLE t0;
REFRESH TABLE t1;


SELECT * FROM t0, t1; -- ' ' 'a'
SELECT ((t1.c0 IS NOT NULL)AND(t0.c0!='')) FROM t0, t1; -- TRUE
SELECT * FROM t0, t1 WHERE ((t1.c0 IS NOT NULL)AND(t0.c0!=''));
-- Expected: 1 row
-- Actual: 0 row


-- also for operators like: IS DISTINCT FROM, <>
```

### Actual Result

`TRUE`

### Expected Result

the second query returns false.

**Comment by matriv** [comment]
The issue is not related to the join, it can be reproduced only by quering `t0` table:
```
cr> SELECT t0.c0, t0.c0 != '' FROM t0;
 
+----+-----------------+
| c0 | (NOT (c0 = '')) |
+----+-----------------+
|    | TRUE            |
+----+-----------------+
SELECT 1 row in set (0.002 sec)
cr> SELECT t0.c0, t0.c0 != '' FROM t0 WHERE t0.c0 != '';
 
+----+-----------------+
| c0 | (NOT (c0 = '')) |
+----+-----------------+
+----+-----------------+
SELECT 0 rows in set (0.003 sec)
```

If `NOT LIKE` is used, it works correctly though:
```
cr> SELECT t0.c0, t0.c0 != '' FROM t0 WHERE NOT (t0.c0 LIKE '');
+----+-----------------+
| c0 | (NOT (c0 = '')) |
+----+-----------------+
|    | TRUE            |
+----+-----------------+
SELECT 1 row in set (0.003 sec)
```

**Comment by matriv** [comment]
The issue is related to `CHAR(3)`, if we create the table with type TEXT (or STRING), it works correctly:
```
cr> CREATE TABLE tbl(c0 text);
CREATE OK, 1 row affected (0.343 sec)
cr> INSERT INTO tbl(c0) VALUES (' ');
INSERT OK, 1 row affected (0.017 sec)
cr> SELECT tbl.c0, tbl.c0 != '' FROM tbl;
 
+----+-----------------+
| c0 | (NOT (c0 = '')) |
+----+-----------------+
|    | TRUE            |
+----+-----------------+
SELECT 1 row in set (0.002 sec)
cr> SELECT tbl.c0, tbl.c0 != '' FROM tbl WHERE tbl.c0 != '';
 
+----+-----------------+
| c0 | (NOT (c0 = '')) |
+----+-----------------+
|    | TRUE            |
+----+-----------------+
SELECT 1 row in set (0.002 sec)
```
The issue drills down to CHAR(3) and the equality operator:
`t0.c0 != ''` -> `NOT t0.c0 = ''` -> `NOT t0.c0 = CAST('' AS CHAR(3))` -> `NOT t0.c0 = '   '`
This happens because we always attempt to cast literal values to the data type of the column, and not the other way around, which enables us to use native LuceneQueries, and not GenericFunctionQuery. If we applied the cast to the `c0` column it would become: `NOT CAST(c0 AS TEXT) = ''` which cannot be translated to a lucene query as there is a function (cast) on the column `c0` of the table.

Checking with Postgres:
```
matriv=> SELECT c0, c0 != '' FROM t0;
 c0  | ?column? 
-----+----------
     | f
(1 row)

matriv=> SELECT c0, c0 != '' FROM t0 WHERE c0 != '';
 c0 | ?column? 
----+----------
(0 rows)
```
it seems that for CrateDB, what is wrong is that we return TRUE when the condition is on the SELECT clause.

Again, in Postgres, if we create a table with VARCHAR instead of CHAR:
```
matriv=> CREATE TABLE tbl(c0 VARCHAR(3));
CREATE TABLE
matriv=> INSERT INTO tbl(c0) VALUES (' ');
INSERT 0 1
matriv=> SELECT c0, c0 != '' FROM tbl;
 c0 | ?column? 
----+----------
    | t
(1 row)

matriv=> SELECT c0, c0 != '' FROM tbl WHERE c0 != '';
 c0 | ?column? 
----+----------
    | t
(1 row)

matriv=> SELECT c0, c0::CHAR(3) != '' FROM tbl;
 c0 | ?column? 
----+----------
    | f
(1 row)

matriv=> SELECT c0, c0::CHAR(3) != '' FROM tbl WHERE c0::CHAR(3) != '';
 c0 | ?column? 
----+----------
(0 rows)

```
So the behaviour regarding the where clause is the same as with Postgres, we need to fix how it's treated when in the SELECT clause.

**Comment by matriv** [comment]
Thank you for reporting this issue @suyZhong ! It has been fixed, and will be available with the upcoming hotfix releases.
