### ISSUE TITLE
IN clause on primary key column does not return all the records if it has multiple values in IN clause.

### ISSUE THREAD

**Issue by vinayakshukre** [crate/crate#16942]
### CrateDB version

5.8.2

### CrateDB setup information

Any number of crate nodes and with 8GB+ memory.

### Problem description

When there are multiple values in the IN clause, query results are not correct. 
Two queries which in theory should return same results, do not return same results.

### Steps to Reproduce

Details about how to reproduce this bug and data required etc are given [here](https://community.cratedb.com/t/in-clause-on-primary-key-column-does-not-return-all-the-records-if-it-has-more-than-5k-inputs/1878/3?u=vinayak.shukre).

### Actual Result

Output of the two given queries is not same.

### Expected Result

Output of the two given queries should be same.

**Comment by matriv** [comment]
@vinayakshukre thx for reporting this issue, It has been fixed and the fix will be available with 5.9.3 hotfix release.
The fix is that for such complex expressions with lots of values for one or more of the pk columns, we need to fallback to a `Collect` plan, as otherwise, with our current algorithm that optimises to a `Get` plan, we are not able to correctly use all the values provided and wrong results (less rows) would be returned.

**Comment by vinayakshukre** [comment]
@matriv Thanks for the fix. I will wait for 5.9.3 hotfix release. BTW, should execution be slower now as it is not using the optimized Get plan?

**Comment by matriv** [comment]
no it shouldn't, the caveat is that if it fallbacks to Collect, you may need to manually REFRESH, or wait for the automatic refresh of table, to make sure you see all recent changes (inserts/updates/deletes)
