### ISSUE TITLE
Use Crate SQL plugin in Elasticsearch

### ISSUE THREAD

**Issue by sim1st** [crate/crate#2038]
I am using Elasticsearch on linux sever but Quering is a little bit difficult

because form of query is not SQL structure.

In crate, there is a sql plugin, so I put this plugin into my own Elasticsearch

Is it possible?

If not, how can I adopt Crate SQL Plugin into Elasticsearch?

Thanks

**Comment by mfussenegger** [comment]
You'll have to use Crate directly. It is not possible to use just the sql module with elasticsearch.
Is there a specific reason you're trying to use the SQL part of Crate with stock Elasticsearch instead of just going with Crate?
Crate already includes all of elasticsearch (a patched version of it, with some additions).

[See also this answer on Stackoverflow](http://stackoverflow.com/questions/30230751/use-crate-sql-moduleplugin-in-elasticsearch)

**Comment by sim1st** [comment]
is it also impossible to previous version of CRATE?
in previous version, the file "/sql/DEVELOP.rst" includes how to build jar file with maven.
I've tried to make jar file of crate-sql-plugin , and adopt to my ES, but doesn't work..

**Comment by mfussenegger** [comment]
In a very early (pre-release) version that was possible. But that was running agaist ES 0.20 or 0.90 and the SQL features that were supported was way more limited than was it supported now.

The `/sql/DEVELOP.rst` was just leftover and never removed.

Still I don't understand why you don't want to use Crate directly?

**Comment by sim1st** [comment]
Cause I just used to operation under ES environment and plugin like head.
I think It is very complicated that moving my huge data and setting new environment ES to CRATE

**Comment by dobe** [comment]
hi @sim1st 

for more background, why this is not possible see https://crate.io/blog/sql-for-elasticsearch/
