### ISSUE TITLE
createStatement(int resultSetType, int resultSetConcurrency) not supported

### ISSUE THREAD

**Issue by proofy** [crate/crate#2120]
I'm using DBeaver to manage many different databases, so I try to do this with great crate too.
But if I'm execute a SQL command, I get this error:
>SQL Error: Connection: createStatement(int resultSetType, int resultSetConcurrency) not supported
  java.sql.SQLFeatureNotSupportedException: Connection: createStatement(int resultSetType, int resultSetConcurrency) not supported

**Comment by chaudum** [comment]
hi @proofy 
the Crate JDBC driver does only support the `TYPE_FORWARD_ONLY` result set type and the `CONCUR_READ_ONLY` result set concurrency, that's why this method raises a `SQLFeatureNotSupportedException`
however, the method should check if the given type/concurrency is supported and only raise an exception if they are not supported. we're going to fix that.

best,
christian

**Comment by chaudum** [comment]
https://github.com/crate/crate-jdbc/pull/70

**Comment by chaudum** [comment]
crate-jdbc 1.7.0 is released

https://bintray.com/crate/crate/crate-jdbc/1.7.0/view
https://github.com/crate/crate-jdbc/blob/master/CHANGES.txt#L5
