### ISSUE TITLE
How to increase the speed of this benchmark?

### ISSUE THREAD

**Issue by mojovski** [crate/crate#2506]
On my local machine (localhost:4200) I created this table:
```
    create table my_table (
        x integer primary key,
        y integer primary key,
        z integer primary key,
        sha1_file string
    );
```
and ran this python benchmark inserting 1Mio elements.
```
from crate import client
import time
connection = client.connect() #(crate_host)
cursor = connection.cursor()
n=100
t0=time.clock()
for x in range(n):
	for y in range(n):
		for z in range(n):		
			cursor.execute("""INSERT INTO my_table
				(x, y, z) VALUES (?, ?, ?)""",
				(x,y,z))
t1=time.clock()
elapsed=t1-t0
print "Inserting "+str(n**3)+" elements took: "+str(elapsed)+" seconds"
```

And I receive:
```
Inserting 1000000 elements took 622.201936 seconds
```

Is there a way to increase the speed?

PS: I need a speed 100x faster than that. :/

**Comment by dobe** [comment]
you should either use execute_many if it is ok for your use-case to batch the inserts (see https://crate.io/docs/projects/crate-python/stable/client.html#inserting-data) 

also a bottleneck is the sequential call you are doing here. try to insert in parallel with threads or prccesses, then it should be faster. 

i don't know the use case, but if you want to import lot of data you might want use copy from, see https://crate.io/docs/stable/best_practice/data_import.html 

in order to be able to insert 160000 rows per second (according to your requirements) you need more clients or use copy from. we achieved about 330k tweet inserts per second on an 8 node ssd cluster with copy from.

**Comment by mojovski** [comment]
Thank you very much! 
The suggestions sound great. I will test them and report my experience here in a few days. :)

**Comment by benjaminrigaud** [comment]
Don't forget to benchmark a cluster (at least 3 nodes): you should get far worse performances on a cluster with sequential inserts. Parallel inserts will help but it may not be enough for your use case.

**Comment by mojovski** [comment]
@dobe , thanks again for all the suggestions! They are really of great value.
So far I applied execute_many, and the insertion of the same data as described in the initial message took **only 10 seconds**. This is a **speedup of 62x**, which is great!
You can find the modified example here: https://gist.github.com/mojovski/e78f916260bfc1d8c08f

I also created some tests with **redis**, and when using the same naiive approach (3-fold for-loops) the speed is 6x higher than in crate.io. When using a similar concept as "insert_many", but called "pipes" in redis, the insertion takes **45 seconds**. 

Next I will try the "copy_from" and also using at least 3 clusters, as suggested by @benjaminrigaud .

Thanks again, and read you later.

**Comment by dobe** [comment]
sounds great! looking forward to see the results!

**Comment by mfussenegger** [comment]
Closing this as the initial question has been answered
