### ISSUE TITLE
Feature request: Improve ElasticSearch integration

### ISSUE THREAD

**Issue by khalidsalomao** [crate/crate#2587]
Crate is great! The idea of "SQL with the NoSql goodies" is what makes crate promising and powerful! 

So why not have full support for ES api and leverage the full power of really having NoSql goodies? There are many SQL databases out there, but a database with support for both APIs is more unique.

For those that already have an ES stack, one of the major problems in adopting crate is having to rewrite every app that does an insert or update... That is my case, we already have lots of applications that use ES api to insert (update and delete) into ES clusters. We would **love** to migrate to crate, but that is not feasible for now.

I think that crate would benefit a lot and gain a larger potential market if it could support inserts with ES api.

**What do you think of these features:**

**1.** sql command to refresh an existing ES index so that Crate can understand and query it.

```
REFRESH TABLE my_index_name;
```

Some Crate features, like partitioned tables, may not be available with this feature, but it would still be extremely useful and powerful...

**2.** ES api hooks/triggers to auto-update Crate if data is indexed using ES api instead of Crate SQL.

Since Crate already uses a fork of ES, what about inserting some code in the insert/update/delete api calls so that Crate are notified and can keep everything in sync?
##

**Comment by mfussenegger** [comment]
Glad you like it.

It is possible to enable the full ES API by setting `es.api.enabled: true` in the `crate.yml` configuration file.
But this is generally done at "your own risk" because we don't test it. You can do stuff with the ES API that we might not have thought of. So by doing stuff via the ES API you can basically break Crate.

Generally 1 Crate table maps to 1 ES index, so if you enable the ES API you'll see indices which are tables in Crate (except for partitioned tables, they're a bit different..)

This means that there actually is no need to sync between Crate Table and ES Index - you'll see with select queries the same kind of data that you'd see if you did an ES search request.

But there are a couple of other issues that you might run into:

For example our table-meta data is stored slightly differently than that of an ES index. So if you create an index using the ES Api, it might be that you see it within Crate but that you'll get errors if you try to query it (depending on columns, analyzers... )

The other way around - creating a table in Crate and then use the ES Api to add records - it might work. But Crate is usually a bit stricter about data validation, so you might end up inserting records which are invalid and would have failed if you tried to insert the same kind of records using crate.
These kind of records might then cause failures if you try to query the data using SQL.

These are just a couple of examples. There might be more stuff.

Anyway, thanks for the feedback.

**Comment by khalidsalomao** [comment]
Thanks @mfussenegger for your fast response!

Actually, I did several tests using `es.api.enabled: true` before opening this ticket! Only after these test that I proposed the above features...

Tested with version 0.51.2
OS: Ubuntu 14.04

**Some of my findings:**
 If you have an existing index, it is possible to force Crate to query it with the following steps:
. Call `CREATE TABLE` with the same index name
. Insert one record using Crate sql `INSERT`

**Shortfalls** of this approach: Crates allows the query to be executed but the results are wrong. It seems that there is some statistics that Crates stores that are not updated in these approach...

**Comment by mfussenegger** [comment]
That's probably because of what I mentioned - the table metadata being slightly different.

Just to clarify. You had a cluster running ES with indices and records. Then at some point stopped that cluster and started Crate which used the same data directory?

I wonder if we should have some kind of ES-to-Crate migration script (or automatic conversion built into crate). Which ideally would leave the indices in a state so that they can still be used with the ES Api and also makes them usable with SQL

**Comment by khalidsalomao** [comment]
>Just to clarify. You had a cluster running ES with indices and records. Then at some point stopped that cluster and started Crate which used the same data directory?

No, it was a brand new Crate cluster with Crate 0.51.2. 
In this test, I just used existing applications to insert data normally using ES api (as it does with a ES cluster). Then to try to query the index, it did several experiments. The one described above was the one with the best results...


>I wonder if we should have some kind of ES-to-Crate migration script (or automatic conversion built into crate). Which ideally would leave the indices in a state so that they can still be used with the ES Api and also makes them usable with SQL

Yes, that would also be an interesting tool to have. But I still believe that the support for ES api inserts is a must and would be mind blowing!

**Comment by BernhardGruen** [comment]
An automatic migration script would be "crate". This way one could access (at least for searches) the new Crate cluster with "legacy" elastic search REST calls. That's a perfect way to migrate applications.

**Comment by megastef** [comment]
+1 for @BernhardGruen migration script and ES compatible index API

Well for indexing it might be very easy to write 'proxy' service in Node.js taking ES bulk requests, and then create SQL for inserts with https://www.npmjs.com/package/node-crate or a "copy from" command.
I have done something similar once (taking http JSON posts, and use Crate SQL for inserts). 
Importing data would work like a re-index job in Elasticsearch.

**Comment by mfussenegger** [comment]
It's been a while since this issue was created and the CrateDB code base has moved a long way since then. Our query engine has diverged a lot from ES since then and we're moving further away from ES as we go.
As such I'm closing this as we're going more in the opposite direction.

For a "mixed" ES/SQL use-case, the SQL functionality added to ES via x-pack might make sense. We're focusing on use-cases and users who go full in with SQL.
