### ISSUE TITLE
Record persistence on restart

### ISSUE THREAD

**Issue by ajermakovics** [crate/crate#2681]
Hi all,

Trying to figure out whether this is expected behaviour. Basically when I have two nodes and one of them goes down then the writes to the remaining one don't seem to persist. 

These are my steps using version  0.50.6 :
- Start two nodes A and B, wait for them to join up.

- Open Console via web interface on node A and run:
```
CREATE TABLE my_table (id integer, primary key (id));`
INSERT INTO my_table (id) values (1);
INSERT INTO my_table (id) values (2);
INSERT INTO my_table (id) values (3);
```
- Stop node B

- Still on node A:
```
INSERT INTO my_table (id) values (4);
INSERT INTO my_table (id) values (5);
```
- Stop node A with Ctrl+C.
- Start node B and wait for it to start up.
- Start node A and wait for it to join

- Again on node A:
`SELECT * FROM my_table limit 100;` returns records 1-3 **only**
The same result after running REFRESH TABLE.

All input appreciated

Andrejs

**Comment by mfussenegger** [comment]
I think the problem in the case you described is that B is recovering it's cluster state immediately - without waiting for A to join - because it isn't aware that there *should* be other nodes joining. It will take the lead and since it never received the records 4 and 5 the won't appear.

Once A joins B already has a "newer" cluster state and the data from A is discarded.

In order to prevent this from happening you can set the gateway recovery settings described in https://crate.io/docs/en/latest/best_practice/multi_node_setup.html?highlight=gateway#gateway-configuration

This way if you start up B it will wait for node A before recovering the cluster state - this way you won't lose the data.the data.

**Comment by mfussenegger** [comment]
Btw. in the next feature release we'll display warnings in the Admin UI and within crash if you connect to a cluster that isn't configured properly to prevent such misconfigurations from occuring.

**Comment by ajermakovics** [comment]
Yepp, gateway recovery settings did the trick. 
Though having default configuration that can discard data seems undesirable. Admin UI warnings will help but only if you are looking at it.

**Comment by mfussenegger** [comment]
I fully agree that it is undesirable. But automatically setting a default is kinda tricky as without explicit configuration it is a unknown how many nodes there are supposed to be.

I'm closing this as the original question/problem is solved. But feel free to open another issue regarding the default configuration if you want to discuss it or have a concrete suggestion how it could be improved.

**Comment by ajermakovics** [comment]
Fair enough, I might just do that. Thank you!
