### ISSUE TITLE
INSERT INTO ... (SELECT ...) command reported as killed

### ISSUE THREAD

**Issue by benjaminrigaud** [crate/crate#3032]
In the past two weeks, I had issues with some commands being reported as killed.

The last one was a INSERT INTO ... SELECT on 200m small documents.
It was executed in crash and got reported as killed after 40m docs: ```SQLActionException[Job killed]```

But in the web interface: the total record kept increasing and the load stayed high (~4)
stats is enabled but I couldn't see it in sys.jobs

A ```kill all;``` really killed it.

1) Is that viable to copy big batch of data with INSERT INTO SELECT?
2) It looks like the command was reported as killed but continued and was invisible from sys.jobs

Ben

**Comment by chaudum** [comment]
Hi @benjaminrigaud 

Concerning your first issue: We've just merged a fix for first this into master yesterday (see #3023). The problem was that we have an internal check if certain jobs are still alive. However in certain conditions, this reported that the job was idle although it wasn't. Now you're able to disable the `keep_alive_timeout` via a setting. We're going to backport the fix to 0.52 and 0.53 now.

Concerning killing jobs: even if you use `KILL ALL` and the the job is invisible in the `sys.jobs` table, it is possible that certain internal requests (that cannot be cancelled directly) are still ongoing and therefore causing the load.

**Comment by benjaminrigaud** [comment]
Thank you.

Concerning the killed status: Crate told me the job was killed but it was still running. a ```kill all``` killed it as expected. It doesn't look like an unkillable request.

**Comment by chaudum** [comment]
@benjaminrigaud can you test the behaviour with the new version `0.52.4` and set the `jobs.keep_alive_timeout` very low, e.g. `1m`? the internal kill should actually have the same behaviour as `KILL`. also, if you still have the logs, did you get any warnings like
`An error occurred while killing context for job ...` ?

**Comment by benjaminrigaud** [comment]
I now use 0.53.1: I'll test it as soon as the 0.53.2 is released :)

**Comment by chaudum** [comment]
@benjaminrigaud ok, we'll let you know when 0.53.2 is ready!

**Comment by joemoe** [comment]
hi @benjaminrigaud, we moved straight to 0.54.0 and probably will never release a 0.53.2. could you test it with 0.54.0?
https://github.com/crate/crate/releases

**Comment by benjaminrigaud** [comment]
Am using 0.54.1. What is the expected behavior if I set a low jobs.keep_alive_timeout?
Will the import be killed pretty fast?

**Comment by joemoe** [comment]
the job will be killed after a short time if it gets idle.

**Comment by benjaminrigaud** [comment]
Ok, but It shouldn't get idle during regular operation?

Thank you.

**Comment by joemoe** [comment]
yes.
