### ISSUE TITLE
SQLActionException - A where clause with no match should not result in an ES query

### ISSUE THREAD

**Issue by l7s** [crate/crate#3095]
Hi, our v0.45.6 cluster from time to time (few times a day) throws exception as below:

    (5000) SQLActionException[A where clause with no match should not result in an ES query]

when running a simple query as

    SELECT COUNT(*) AS count FROM cdr WHERE customer_id = ?

Any suggestions what might be causing this error and how to troubleshoot it much appreciated.

Regards,
Chris

**Comment by chaudum** [comment]
hi @l7s 
First of all, I strongly recommend that you upgrade your Crate cluster to the most recent version (`0.52.4`).
In earlier versions Crate has used Elasticsearch queries to perform certain tasks (in your case a count task). These have been continuously replaced in newer versions.
Your bug prob occurs because there is no customer with the given `customer_id` resulting in a "no match", thus not being able to perform a ES query task).

**Comment by l7s** [comment]
Hi, thanks for prompt reply. I had a deeper look based on your feedback and indeed the problem relates to incorrect value of `customer_id`. However it is not non-existing customer causing the problem. This works just fine retuning correct result `0`:

    SELECT count(*) FROM cdr WHERE customer_id = 0

the exception is caused by query as below:

    SELECT count(*) FROM cdr WHERE customer_id = null

Another question: when upgrading from `0.45.6` to `0.52.4` can we just stop the cluster, replace Crate binaries keeping data/log directories and start the cluster again? Is data/log created by  `0.45.6` compatible with `0.52.4`?

**Comment by chaudum** [comment]
whenever you update across "major" versions (e.g. `0.45.6` -> `>=0.46.0`), you need to stop the complete cluster, then update, and only then start all nodes again.
rolling upgrade is **not** supported because the internal protocol might have changed slightly.

also make sure you have the `minimum_master_nodes` and [gateway](https://crate.io/docs/reference/configuration.html#metadata-gateway) settings set correctly.
in theory all should be fine, but you should try out on a testing cluster first and make sure you have a complete backup of your data ;)
