### ISSUE TITLE
settings for aggregation functions

### ISSUE THREAD

**Issue by eshubin** [crate/crate#3361]
In current API for aggregation functions all arguments are passed to AggregationFunction.iterate.
Although in some cases some arguments might be needed only in AggregationFunction.reduce or even AggregationFunction.terminatePartial.

A good  example of such function is calculating quantile or percentile of discreet value in table.
The function could be defined as percentile(<colum>, <level>). _Column_ is needed in each iterate callback, whille level is needed only on _terminatePartial_.

**Comment by joemoe** [comment]
hey @eshubin, thanks for your suggestion. we'll have a look into it.

**Comment by dobe** [comment]
hi @eshubin 
because of the way how functions are serialized internally this would require an interface change and a refactoring internally, so i think that this will not be done anytime soon.

however, you can ensure that only literals are used for your static arguments by overriding `normalizeSymbol` then you can ignore this static argument after storing it in the first  `iter` call into your state object.
