### ISSUE TITLE
Aggregate Performance: Elasticsearch vs Crate.IO

### ISSUE THREAD

**Issue by githubmui** [crate/crate#3389]
I found an article which compares Elasticsearch  vs. Crate.IO aggregation performance:
Have a look at "https://www.anchormen.nl/jdbc-driver-for-elasticsearch/" paragraph "Crate".

They said that Crate.IO aggregation is around 7 time slower that native Elasticsearch one.
Does this match with your tests?

**Comment by benjaminrigaud** [comment]
If they did their tests with an old version (<0.53.1), they must have hit this issue https://github.com/crate/crate/issues/2933

I didn't observe such differences (I had similar results query by query) when I tested the 0.53.1 release.

**Comment by dobe** [comment]
PS: i think the difference comes from the shard size setting of elasticsearch. it basically trims results per shard and is not 100% accurate, since not all rows are taken into account when results are sorted on the aggregation. see https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-bucket-terms-aggregation.html#_shard_size_2
