### ISSUE TITLE
Scalar Check Functions for "Generated Columns"

### ISSUE THREAD

**Issue by githubmui** [crate/crate#3420]
Hi,
in calculation-expressions for "Generated Column" it's hard to check, if there are invalid or problematic column values (0, NULL etc.).
Scalar functions like Min(), Max(), Coalesce(,,,) or a (condition?value1:value2)-operator would be a great help to avoid errors.
Cheers.

**Comment by joemoe** [comment]
hi @githubmui, that's a good suggestion. i'll add this to our backlog.

**Comment by githubmui** [comment]
Thx, joemoe!

**Comment by dobe** [comment]
thx, @githubmui i think you mean conditional functions http://www.postgresql.org/docs/current/static/functions-conditional.html in general. we already have coalesce on our backlog, however since there are so many things on our backlog, i would not expect this soon. as always contributions are welcome - if you consider contributing this functionality we will help you to get started.

best, bernd

**Comment by aelesbao** [comment]
@githubmui this feature is now on our master branch and will be included in the next release

**Comment by aelesbao** [comment]
https://github.com/crate/crate/pull/3772
