### ISSUE TITLE
How to scale out without CRITICAL ERROR message?

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#3978]
We have 3 nodes in Crate Cluster with 0.55.2, and We want to scale out with 1 node.

The full configuration file of new nodes as follows:

``` bash
bootstrap.mlockall: true
node.name: "crate172"
gateway.expected_nodes: 4
gateway.recover_after_nodes: 2
discovery.zen.minimum_master_nodes: 3
discovery.zen.ping:
  multicast.enabled: false
  unicast.hosts:
    - crate124:4300
    - crate172:4300
    - crate175:4300
    - crate176:4300
es.api.enabled: true
cluster.name: bi_crate
cluster.graceful_stop.min_availability: full
cluster.graceful_stop.reallocate: true
cluster.graceful_stop.timeout: 10s
cluster.graceful_stop.force: true
node.master: true
node.data: true
stats.enabled: yes
indices.store.throttle.type: all
indices.store.throttle.max_bytes_per_sec: 100mb
indices.memory.index_buffer_size: 30%
indices.memory.min_index_buffer_size: 256m
indices.memory.min_shard_index_buffer_size: 128m
threadpool.index.type: fixed
threadpool.search.type: fixed
threadpool.get.type: fixed
threadpool.bulk.type: fixed
threadpool.refresh.type: scaling
cluster.info.update.interval: 10s
bulk.request_timeout: 10m
udc.enabled: true
udc.initial_delay: 1m
udc.interval: 30m
```

Yet, the existed nodes don't need to restart, and the configuration of existed nodes have no changes.

> gateway.expected_nodes: 3
> discovery.zen.minimum_master_nodes: 2

And the web pages of crate-admin prompt following message:

``` bash
CRITICAL
The setting 'discovery.zen.minimum_master_nodes' must not be less than \
half + 1 of eligible master nodes in the cluster. It should be set to \
(number_master_nodes / 2) + 1. https://cr8.is/d-check-1

CRITICAL
The value of the cluster setting 'gateway.expected_nodes' must be equal to \
the maximum/expected number of master and data nodes in the cluster. https://cr8.is/d-check-2
```

The `discovery.zen.minimum_master_nodes` could be updated online via following command:

> SET GLOBAL PERSISTENT discovery.zen.minimum_master_nodes = 3;

Yet the `gateway.expected_nodes` parameter work after restart according the official documention.

How can I update `gateway.expected_nodes` parameter without restart the whole nodes of Crate?

**Comment by celaus** [comment]
Hi Robin, so the settings `gateway.expected_nodes` and `gateway.expected_nodes` are both settings the cluster has to be restarted for in order to properly apply them, since they determine whether the cluster state should be recovered from disk or taken from the current cluster - nothing that ever occurs at runtime. Consequently the settings don't have to be updated until the cluster can be safely restarted. For new nodes the setting can be updated and they also should not show the warning. 

These messages are warnings that should show sub-optimal configuration and, depending on the warning/what you did, can be ignored fairly safely, which is also a feature that is upcoming, so that these checks can be acknowledged. 

As a course of action, I would recommend to update the yml files of the old nodes and leave them as they are until there's a time where a rolling restart can easily take place without harming your availability. 

All the best, Claus

**Comment by dbarobin** [comment]
Thanks.

Sincerely, Robin
