### ISSUE TITLE
Regex queries hang when using asterisk

### ISSUE THREAD

**Issue by gadnuk** [crate/crate#4359]
We are currently using VERSION: 0.54.9

As per the changelogs, regex queries have had improved performance along with some bug fixes for invalid regex. However, we are still seeing the queries hang if we do it like this:

select * from table where name ~* '.**eric.*';

If I substitute the second asterisk with some other special characters, then the query runs fine. However, the presence of the asterisk right after the wildcard throws it off.

**Comment by celaus** [comment]
Hi @gadnuk - thanks for noticing! 

I think it's because an asterisk is a regex special character and actually would need to be escaped :) - while not throwing an exception is not ideal, this has been changed more recently and works fine in 0.56.3 (i.e. it provides a proper exception). 

``` 
select * from mytable where name ~* '.*\*eric.*';
``` 

Cheers, Claus

**Comment by gadnuk** [comment]
@celaus ,

Thank you so much for your response! We will be upgrading to the latest stable version soon. In the meantime, we are adding some validation underneath to escape special characters present in the search text so that we can handle such queries where an exception may not be thrown.

Kindly close this issue.

Cheers,
Eric.
