### ISSUE TITLE
what's the copy from process?

### ISSUE THREAD

**Issue by hellof3** [crate/crate#4369]
Hi,I have a question about the copy from process. Now i have a three node cluster,the json file i want to load is on one node's local disk,so the only crate node will analyzer the sql,make plan,execute and finally send the shards and replicas to other nodes, or it will send data(file) to other nodes and many nodes execute?I'm very confused,Thank you very much.

**Comment by celaus** [comment]
Hi, it depends where you are copying from: https://crate.io/docs/reference/sql/reference/copy_from.html ... but in your case only those nodes where the file is available will import the file and insert the data regularly, there's no sending files around over the network ;)
Cheers, Claus

**Comment by hellof3** [comment]
hi, @celaus ,thanks for replying,is it means,the only one crate node will do the index process to create indexes and make it to shards and send shards and replicas to other nodes,right?if the file is very big,do i need to copy the data to very crate node?

**Comment by celaus** [comment]
No, it inserts the data just like any other insert: The node where the file is located creates a row and figures out where this row needs to go. With copy from a couple of these rows will be gathered (if they belong to the same shard) and then shipped off to the node holding that shard. The responsible node (for the shard) will then insert the row into its index. 

It is certainly recommended to *split* large files and distribute them in the cluster since it improves concurrency. Ideally you also import directly into certain partitions! Don't copy the source file unless you want to import it multiple times.

**Comment by hellof3** [comment]
@celaus thanks,i understood,the node will send rows to other nodes  which hold the particular shards and then many nodes will index the rows.
