### ISSUE TITLE
Data access in scalar function

### ISSUE THREAD

**Issue by WalternativE** [crate/crate#4580]
Hello!

I was wondering if there is any way to access data within the crate cluster while executing a scalar query.
Are there any utilities exposed similar to a lucene query parser or a JPA entity manager which could be used to execute a query - or would opening up another JDBC connection be my only choice if I try to emulate a stored procedure like behaviour?

Regards
Gregor

**Comment by mfussenegger** [comment]
That's currently not possible.

Could you explain your use-case a bit more?

**Comment by WalternativE** [comment]
I wanted to emulate the behavior of a SQL function/stored procedure. For example: for a given id (eg of a row in a person table) I would return the full name with academic title (academic titles would have been stored in different tables). Within the function the id would have been used to join the title relations to the person table, concatenate the fields and return a single value as a string.

Is this example understandable enough or should I add additional information for clarification purposes?

**Comment by mfussenegger** [comment]
If I understand you correctly you want to do something like a subselect or join
within a scalar function?

That's not possible unless you really use a JDBC connection within a scalar
function, as you mentioned. 

But if you do that it's going to be horrible slow.

Since Crate is distributed any data access call within a scalar function could
hit another node. The network latency alone for any request is about ~0.200ms.
E.g if you select 1000 rows and execute this scalar function per row you're
already at 200ms only calculating the time spent on the wire.
What's worse, since the scalar function API is synchronous you'd always block a
whole thread during any IO.
This could quickly lead to the whole cluster becoming unresponsive.


As long as we don't have stored procedures I think the best option to put logic
into a centralized place is to create some kind of webservice before Crate and
have clients talk to that webservice instead of CrateDB directly.

**Comment by WalternativE** [comment]
Thank you for your extensive answer. The web API approach would have been my plan B - should do well enough.

Do you have any information on when stored procedures should be implemented in CrateDB?

**Comment by mfussenegger** [comment]
@WalternativE can't give you any information about stored procedures.
But there is another [gh issue about stored procedures](https://github.com/crate/crate/issues/4616#issuecomment-268823414)

I'll close this because the original question has been answered - any further discussion or input regarding stored procedures can go into the other issue.
