### ISSUE TITLE
Group by aggregation for table joins

### ISSUE THREAD

**Issue by bputt** [crate/crate#4672]
**Use case**: Being able to aggregate data across multiple tables and grouping by certain fields.

**Feature description**:
Let's say I have two tables: tableA, tableB. tableA contains all of my metadata and tableB contains important timing information relevant to a record in tableA.

For example:
tableA contains the following columns:

```
id STRING,
browser STRING,
browserversion STRING,
os STRING
```

tableB contains the following columns:

```
testid STRING,
testname STRING,
startdate LONG,
enddate LONG,
time STRING
```

Example query:
```
SELECT avg(tableb.time), tableb.testname FROM tableb INNER JOIN tablea on tableb.testid = tablea.id GROUP BY tableb.testname;
```

Error that I currently get:

```
ValidationException[GROUP BY on JOINS is not supported]
```

**Comment by bputt** [comment]
I've tried to combine the data from the joined tables into tableA to see if I could query it, but receive the error:

```
SQLActionException[UnsupportedFeatureException: unknown function: avg(long_array)]
```

New table schema:

```
id STRING,
browser STRING,
browserversion STRING,
os STRING,
tests array(object as (
  name STRING,
  startdate LONG,
  enddate LONG,
  time STRING
))
```

New SQL:

```
SELECT avg(tests['time']), tests['name'] FROM tablea GROUP BY tests['name'];
```

**Comment by joemoe** [comment]
hi @bputt, 

we are already working in the area of group by in joins, but we need to finish some ground work in order to get this running in performant way. we hope to have this soon (somewhen at the end of q1 2017 or q2). i can't promise anything, just tell you that we are aware of it, we would like to have it in cratedb and we are working in that area.

we also don't support aggregations on arrays. i added this to our backlog.

thanks for writing the issue.

cheers, 
johannes

**Comment by tqyq** [comment]
+1
thanks

**Comment by RichardLindhout** [comment]
What is the status on this issue?

**Comment by mfussenegger** [comment]
We've merged support for GROUP BY on joins via https://github.com/crate/crate/pull/5339 - it'll be part of the next feature release (1.2)
