### ISSUE TITLE
excuse me, seek a good way to improve the performance of writing data in the case of massive data by CrateDB jdbc

### ISSUE THREAD

**Issue by aaronhadoop** [crate/crate#5061]
**CrateDB version**: crate-1.0.4

**JVM version**: 1.8.0_111

**OS version / environment description**:

**Problem description**:
I have six machines in my CrateDB cluster, two machines with sata disk, two machines with ssd disk and two machines acting as client. I have 80MB per second to write into CrateDB by cratedb jdbc, but writing too slow causing the data loss.

do you have some good suggestion to raise the write speed? such as some configuration items in crate.yml or some other suggestion. thankyou.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @aaronhadoop,
how are you writing to CrateDB? do you use bulk insert? 
how does your data look? how much rows should be written per second?
how many clients try to write?
how many shards do you have?
is your table/are your tables partitioned?
we need to have more insights in order to provide you feedback on this.
cheers, johannes

**Comment by joemoe** [comment]
hi @aaronhadoop, do you have some answers?

**Comment by joemoe** [comment]
@aaronhadoop, i'm gonna close this now. if you have further information, please reopen it.
