### ISSUE TITLE
group by with left join didn't work

### ISSUE THREAD

**Issue by monosize** [crate/crate#5909]
**CrateDB version**: 2.0.4

**OS version / environment description**: docker image installation

**Problem description**:

I want to select items with no relation to table product in table xsell and want to group them by column sku.

product table with 3300 items - multiple columns, primary key is column ‘sku’
xsell table with 4600000 items - three colums: sku, cross_sku, tstamp

Here is my query: SELECT x.sku FROM xsell x LEFT JOIN product p ON p.sku = x.sku WHERE p.sku IS NULL GROUP BY x.sku;

crate db is running and running - no result - I must restart crate db

Without GROUP BY it’s working?!
Tested locally and on extra server with version 2.0.4 and 2.0.3 ( docker install ).

Is my query wrong or has crate db problems with GROUP BY?
Also tested with mysql. No problems, the query was finished after 1.6 seconds.

**Steps to reproduce**:

SELECT x.sku FROM xsell x LEFT JOIN product p ON p.sku = x.sku WHERE p.sku IS NULL GROUP BY x.sku;

see log file [crate.txt](https://github.com/crate/crate/files/1135497/crate.txt)

**Comment by jodok** [comment]
please can you provide the full schema and sample data?

**Comment by monosize** [comment]
here are the schemas.
[schema-product.txt](https://github.com/crate/crate/files/1135553/schema-product.txt)
[schema-crossselling,txt](https://github.com/crate/crate/files/1135554/schema-crossselling.txt)

**Comment by jodok** [comment]
thanks! please can we also get some sample data? preferably in a format the COPY FROM could read. you can also share them private with jodok@crate.io

**Comment by matriv** [comment]
Hello @monosize,

We reproduced your schema and data and run the query. The query responded back after 22mins on a 8 node cluster and after 35 mins on a local developer's machine. There is nothing wrong with the execution plan of the query and the problem is that it's just slow. It needs to process almost 16 billion rows, (cartesian product), filter out the non matching rows (IS NULL) and apply the group by which basically a DISTINCT.

**Comment by monosize** [comment]
Hello @matriv ,
Thank you for your quick response. 
What options exist to speed up the query, because in MySQL it took 1.6s ( on the local machine it took 2s (empty cache) ) same data with a reduced product table - only one column for the sku field.

**Comment by matriv** [comment]
@monosize 

My guess is that MySQL (as PostgreSQL) will translate this query to an anti-join meaning that it would be equivalent to: ```SELECT x.sku FROM xsell x WHERE NOT EXISTS (SELECT 'x' FROM product p WHERE p.sku = x.sku) GROUP BY x.sku;``` which we don't currently support.
Another option since product table is much smaller than xsell would have been to write it like:
```SELECT x.sku FROM xsell x WHERE x.sku NOT IN (SELECT p.sku FROM product p) GROUP BY x.sku;``` which we also don't at the moment.

So, currently the only option would be to write it with literals:
```SELECT x.sku FROM xsell x WHERE x.sku NOT IN ('value1', 'value2', ...);```
where the values are the result of ```SELECT sku FROM PRODUCT```

**Comment by matriv** [comment]
@monosize

You could also use the following query:
```SELECT x.sku FROM xsell x WHERE NOT x.sku = any(select collect_set(sku) FROM product) GROUP BY x.sku;```

**Comment by monosize** [comment]
@matriv 

That's much better ;-) It took now 8sec!

**Comment by matriv** [comment]
@monosize 

Happy to help.
