### ISSUE TITLE
Unducumented response when uploading BLOB

### ISSUE THREAD

**Issue by l7s** [crate/crate#6017]
**CrateDB version**: 2.0.4

**JVM version**: 1.8.0_60

**OS version / environment description**: Debian 7 64bit

**Problem description**:

According to [docs here](https://crate.io/docs/crate/reference/blob.html) when uploading a blob via PUT request one should receive 201 or 409 responses. However from time to time (once every 30-50 uploads) we are getting 307 with Location header pointing to a different node in our 4 nodes cluster .

Could you please let me know (and possibly update docs for the benefit of others) what is the meaning of 307 response when uploading a blob?

Regards,
Chris

**Comment by mikethebeer** [comment]
@l7s thanks for the hint. The `307` temporary redirect response is expected because it informs the client that the blob gets stored on a different node than requested. The [Download BLOB](https://crate.io/docs/crate/reference/blob.html#download) section shows this in a note:

> Since the blobs are sharded throughout the cluster not every node has all the blobs. In case that the GET request has been sent to a node that doesn’t contain the requested file it will respond with a 307 Temporary Redirect which will lead to a node that does contain the file.

Same as for `GET` this is also valid for `PUT` and `HEAD` requests (see https://github.com/crate/crate/blob/2.0/blob/src/main/java/io/crate/http/netty/HttpBlobHandler.java#L85)

However, we will move this note in the reference docs to a general point that it this belongs to both.

**Comment by l7s** [comment]
Thanks for explanation. Closing this issue now.
