### ISSUE TITLE
Crate 2.1.5 performance very slow and data missing observed on docker container/.tar/.deb package.

### ISSUE THREAD

**Issue by AbrarMalik** [crate/crate#6192]
**CrateDB 2.1.5**:

**JVM 8 UPDATE 144**:

**Windows Server 2012 R2, Ubuntu 17.04/16.04, Docker container/ bare system deployment .tar or .deb package**:

**Crate 2.1.5 performance very slow and data missing observed on docker container/.tar/.deb package.**:

1.  We are using the table which have 20 or more number of columns
2. 50 writes per second are being on crate
3. I have tested this 50 writes per second with Integration objects AnE archiver
4. I also tested it with crate db bench marking tool cr8 as well by using the command (cr8 insert-fake-data --hosts 10.1.11.238:4200 --table processdata3 --bulk-size 50 --num-records 100). In this command only write 100 records with bulk size=50, just 50 records get put into the crate and 50 get lost. A high amount data missing observed. 

**Steps to reproduce**:
- I have attached the table schema herewith, you can create the table and start dumping data into this table by using cr8 tool, you will find the data loss in crate.

[Processdata_table_schema.txt](https://github.com/crate/crate/files/1248337/Processdata_table_schema.txt)

**Use case**:

**Feature description**:

**Comment by seut** [comment]
@AbrarMalik Please explain how you observe that data got lost. Are you doing a `refresh` after the inserts (CrateDB is eventually consistent)?

**Comment by seut** [comment]
@AbrarMalik As I already mentioned here https://github.com/crate/crate/issues/6053, your table definition includes all columns as primary keys. this doesn't make sense to me, is this really what you want?

**Comment by AbrarMalik** [comment]
@seut Thanks for response.
I did not refresh after insert.
We need uniqueness in records of table that's why we use all columns as Primary key. We want this thing because we already use the same table schema in MS SQL table so that now we want this crate table as well.

**Comment by seut** [comment]
@AbrarMalik If you're running this on 1 node, you are probably running into the `wait_for_active_shards` timeout, see https://crate.io/docs/crate/reference/en/2.1/sql/reference/create_table.html#write-wait-for-active-shards. If so, I'd recommend to change the `number_of_replicas` to a dynamic value like `'0-1'` to let crate decide if enough nodes are available to configure replicas. (thats why `0-1` is also the default value since  v2.0.1). Or just set it to `0`.

**Comment by seut** [comment]
@AbrarMalik Related to `refresh` (https://crate.io/docs/crate/reference/sql/refresh.html), one can only see records in realtime if queried by the full primary key, means all columns defined as primary key must occur inside the where clause. Otherwise not all records will appear at the results if no explicit `refresh` was made. See also https://crate.io/docs/crate/guide/overview/storage_consistency.html#consistency.

**Comment by AbrarMalik** [comment]
@seut I have tried with your suggested settings but still data loss and low performance issue observed.  Please keep in mind i have test the settings with whole number of columns as PK.

**Comment by mfussenegger** [comment]
I think what you observe as "data loss" might very well just be de-duplication
due to the primary key. (At least with `cr8 insert-fake-data` that's likely the
case as some of the random value provider have a low cardinality)

Also keep in mind that `insert-fake-data` is *NOT* designed to do benchmarking
or throughput tests. Some of the random value provider are quite slow.


Could you do some tests with real data instead? If you can generate a JSON
file, using `cat mydata.json | cr8 insert-json` would give you a better idea.


Also, I think you'd greatly benefit from changing the schema. Having all
columns as primary key is far from ideal for how the Crate (especially the
storage part) works.

**Comment by joemoe** [comment]
hi @AbrarMalik, did @mfussenegger s comments help you?

**Comment by AbrarMalik** [comment]
@joemoe I know that cr8 generate duplicate data. So i have test it without any PK in schema and write the data from AnE archiver, 50 records per seconds, still observe data loss and performance issue.
I dont know what changes you incorporate in crate 2.2.0 but it quite better performance and less data loss observer in this case.
I think by comparison between crate 2.1.5 and crate 2.2.0, you would be able to find the root cause of issue.
In case of crate 2.1.5: Only 15 to 20 records per seconds were logged into crate from 50 records per second.
In case of crate 2.2.0: 40 to 47 records per second are being logged.
I have seen writes in Monitoring Tab of crate.
Performance is better and less data loss observed in crate 2.2.0.

**Comment by mfussenegger** [comment]
Could you post the updated schema without any PK? In `cr8` there was a bug which broke the random data generation. (See https://github.com/mfussenegger/cr8/issues/174)

How are you measuring the requests/s? If this is based on the output from `cr8` that is flawed with only 1000 records, as the duration is too small. `cr8` displays a time-based average.  Also, you'd have to calculate `duration / bulk_size` to get the number of inserts.

You'd get better metrics by generating a file containing the records in json line format (1 json string per line) and using cr8 insert-json

**Comment by AbrarMalik** [comment]
@mfussenegger I have uploaded the schema file when logged the bug, you can see and remove only the PK, the rest of schema will remain without PK.
As i have commented that performance of 2.2.0 is quite better than 2.1.5/2.1.6. This observations are with PK, use these columns "PRIMARY KEY ("servernodename", "subscriptionname", "sourcename", "eventtime", "eventtime_ms", "message")" from them.

**Comment by mfussenegger** [comment]
> As i have commented that performance of 2.2.0 is quite better than 2.1.5/2.1.6.

Does this mean your problem is now resolved?

If not, please follow the advice we've outlined so far.

So far this looks like a measurement error or configuration issue. Not a bug in
the software. While we try to fix bugs quickly - no matter who reports them, we
can only provide limited troubleshooting support for open source users. In case
you need further assistance, you might want to consider one of the paid support
options. See https://crate.io/pricing/

**Comment by AbrarMalik** [comment]
@mfussenegger We took the paid support as well from crate, we did a one day workshop with crate.
And i never mention that issue has been resolve i just comment that testing release 2.2.0 performance is better than crate 2.1.5.
In crate 2.1.5, 17 to 30 records insert into the crateDB but in case of crate 2.2.0, 35 to 45 records being log into crateDB.
I mean that you can fiure out the issue cause. If you have any concern, please feel free
