### ISSUE TITLE
Docker documentation (swarm setup) is 100% unusable/incorrect causing setup failures

### ISSUE THREAD

**Issue by CollinChaffin** [crate/crate#6200]
**CrateDB version**:
Latest on latest Docker

**JVM version**:
ANY

**OS version / environment description**:
ANY

**Problem description**:
#6151 Why on earth was this closed?  Your Docker docs are 100% incorrect and out of date, and yet Crate is trying to sell itself as the new go-to on Docker?  The only real reference docs for setting up this product on Docker swarm (what it claims is it's strength) just cost us hours of hair pulling and after we determined the SET UP docs were WRONG and had to find other docs to get it set up, we still cannot connect once running probably because those params are also wrong.

This doc:
````
https://crate.io/docs/crate/guide/getting_started/scale/docker_swarm.html
````
Should be TAKEN DOWN.  It's wrong.  The switches do not even work and require changing from -Cdiscovery (as shown in your docs) to -Des.discovery and all the other config lines rendering the entire swarm guide not only unusable, but are actually costing companies time and money who attempt to evaluate your product using incorrect documentation.  Despite issue #6151 being closed, nothing is actually corrected and this is not the first Crate issue I have seen prematurely closed like this.

When it is not just reference docs but follow-along STEP BY STEP docs and then the commands printed are incorrect, it really takes away from confidence that the underlying product will be valuable to by business and replace the other databases we have running.

**Steps to reproduce**:
Take the above URL work-along and please create an up to date VIDEO showing how those commands/steps actually work to produce a working docker swarm service as stated.  I cannot actually find another site or human being that can actually demonstrate that this product really can and does function on Docker swarm and would love to see an updated correct doc to utilize to set it up and actually see it function properly in swarm.

**Use case**:

**Feature description**:

**Comment by CollinChaffin** [comment]
Forgot to add that on Crate's own site, here is yet another doc with 100% different config commands (albeit some more correct despite being older) but that also do not appear to correctly create a working "simple" db service on docker swarm:
````
https://crate.io/a/deploying-crate-with-docker-machine-swarm/
````
Since Crate is heavily selling itself with "CrateDB and Docker are a great match thanks to CrateDB’s shared-nothing, horizontally scalable architecture that lends itself well to containerization" - it would be very helpful to have any single step by step document to show just how "easy" this is to get working on a quick 3 node swarm.  The docker and swarm piece takes me approx 3 minutes and can deploy anything else to it - in fact have one running on this laptop in vmwareworkstation machine driver with same results - the "-C" switch is puked back by Crate as invalid per the logs when attempting to start the successfully created 3 node service - which then of course loops infinitely attempting to restart the broken service with the bad switches.  However, when mishmoshed with "-Des" switches, the service is successful and even starts on all 3 nodes but we have yet to actually connect to it.

Again, we have litereally had multiple people follow the above doc slowly step by step and it is unanimous that as easy as it may be to spin up Crate on anything BUT Swarm, the very strength that propelled Crate to the top of our list for shared-nothing dbs on Docker is also the one scenario that with multiple heads together, we simply cannot make work.  So, a single up to date one page quick start doc for Crate specifically on a basic 3 node swarm (as originally written) would be very helpful.

**Comment by joemoe** [comment]
Hi @CollinChaffin,

yes, we identified some issues on https://crate.io/docs/crate/guide/getting_started/scale/docker_swarm.html.
They were introduced with the latest version of CrateDB (2.1.x).
We will fix them. If you use `crate:2.0.6` instead of `crate:latest` it works.

We are sorry that this issue appeared. It is hard to automatically test a docker machine setup but we will try to include this into our tests. Most of our documentation is automatically tested.

On the matter of premature closed issues: the one you are referring to is actually an pull request with the purpose of moving documentation to a new place. If you don't agree with us by closing other issues feel free to open them any time, it would in this case help us to be more specific in your feedback.

The second link you are referring to is an blogpost from early 2015. https://crate.io/a/deploying-crate-with-docker-machine-swarm/ (Which is made clear on the very top of the page) Docker moved on, CrateDB moved on. So yes, this blogpost is outdated now.

On your requests: no, we won't create a tutorial video as this will be outdated with the very next version of CrateDB and is even harder to maintain and automatically test. Just recently we had a webinar about Docker Swarm and CrateDB, but this was also using version 1.1.6. http://go.cratedb.com/wb-2017-docker.html?utm_source=resource-library&utm_medium=web-direct

CrateDB is an open source product that helps a lot of people making use of their machine data (also a lot of them are using Docker). I'm feeling truly sorry for everyone wasting time by following a wrong documentation in our docs. We are trying hard to answer and fix issues as fast as possible.   Giving specific feedback helps a lot. The only issue I could extract of your feedback is that the parameters don't work any more which conflicts with the issue title.

**Comment by chicco785** [comment]
Hi @CollinChaffin,
we use CrateDB, as other Open Source. Despite documentation issues may have spot (and let me say that there are many communities backed by thousands of developers where docs are much worst, to not say about licensed software...), I think is a pretty good piece of software, quite competitive in the timeseries landscape.
What is nice about OS communities (may not be the case for crate doc - have to check), is that you can contribute by fixing bugs, including ones in the documentation.

Take care
