### ISSUE TITLE
Packaging: Past versions of packages are deleted from APT repositories.

### ISSUE THREAD

**Issue by jeffnappi** [crate/crate#6557]
We automate Crate installation via the use of Debian packages. I would like to be able to pin the version number and be able to provision systems using the same package version and then upgrade when we are ready.

Currently it seems that only the most recent version is being kept in e.g. https://cdn.crate.io/downloads/deb/stable/dists/xenial/main/binary-amd64/

Would it be possible to keep old releases available so that one could for example `apt-get install crate=2.1.7`

Thanks!

**Comment by joemoe** [comment]
hi @jeffnappi, we are already looking into that as another user reported something similar. see the discussion here: https://askubuntu.com/questions/977160/install-a-specific-version-version-not-listed-using-madison we'll keep you posted.

**Comment by Autophagy** [comment]
Hey @jeffnappi - This is because we were using the reprepo tool to manage our debian and ubuntu repositories, which unfortunately has the limitation of only allowing one version per package and distribution. We will be moving our release infrastructure to use something that allows us to keep old releases available. :slightly_smiling_face:

**Comment by JAC2703** [comment]
In addition to this, more recently we're missing some of the newer builds for older distros - in my case Debian Xenial.

https://cdn.crate.io/downloads/deb/stable/pool/main/c/crate/

**Comment by jeffnappi** [comment]
@JAC2703 I would open a separate issue for that! It looks like there's *only* builds for `artful` now.

**Comment by Autophagy** [comment]
@JAC2703 @jeffnappi Thanks for bringing this to our attention! Yeah, it looks like only artful builds have been uploaded. We'll look into this & let you know when the other distributions are up. :slightly_smiling_face:

**Comment by JAC2703** [comment]
Sorry for late response. Ticket raised under #7175

**Comment by mfussenegger** [comment]
It's been a long time since this got raised, but we finally made some changes to our packaging pipeline and as part of that we now preserve older versions in the packages index.

There is a new repository: https://cdn.crate.io/downloads/debian/stable/ - we didn't redeploy old packages. For now only 5.5.1 is available.
