### ISSUE TITLE
Tableau Integration

### ISSUE THREAD

**Issue by everlytics** [crate/crate#6604]
Hi, Can you provide a link to the odbc driver. I can't seem to be able to find it on your website.
The link to tableau connectivity on this page: 
https://crate.io/docs/crate/guide/en/latest/tools/dataviz.html
does not seem to lead to the relevant page.

**Comment by mikethebeer** [comment]
@everlytics thanks for reporting this. The Tableau section in the Data Viz guide seems to be outdated. We don't support ODBC anymore. Instead we recommend to use the Postgresql .NET driver instead. A patched version of the official Npgsql Project is available for download here https://github.com/pircher-software/npgsql/releases/tag/v3.3.0

Keep in mind that you need to install the driver in the GAC (Global Assembly Cache) so that 3rd party applications find the installed driver.

However, the usage of this version of Npgsql is not tested with Tableau Desktop - So it could be that you run into issues there. I'll put this issue on our internal backlog so that someone of Crate.io can take a look at this and test this.

**Comment by everlytics** [comment]
@mikethebeer Thanks for the clarification.

**Comment by mfussenegger** [comment]
We've made some compatibility improvements (available in the upcoming 3.2 release) that will allow users to use [postgres odbc](https://odbc.postgresql.org/)
