### ISSUE TITLE
feature request: union and limit

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6704]
**CrateDB version**: 2.5.0 (testing)

**JVM version**: 1.8.0_151

**OS version / environment description**: CentOS Linux release 7.4.1708 (Core)

**Problem description**:

Happy new year!

I think, supporting union is great.

But, there is some issue using "limit" and "union all" on my first test.

following query occurs error.

![image](https://user-images.githubusercontent.com/2795798/34472302-4fca574a-efa2-11e7-8cc5-e0515679ab08.png)

what I was about to do is. (union 2 query summary using limit. look carefully parenthesis.)

`(select count(\*) from logs limit 1) union all (select count(\*) from logs limit 1);`

but next query works on crate.

`select count(\*) from logs union all select count(\*) from logs limit 1;`

may be **limit** logically works like this on crate.

`(select count(\*) from logs union all select count(\*) from logs) limit 1;`

to solve this, on crate, I should use like this.

`select * from (select count(*) from logs limit 1) a union all select * from (select count(*) from logs limit 1) b;`

this is not straightforward.

Shortly, I hope this query works. this syntax also works on postgresql.

`(select count(\*) from logs limit 1) union all (select count(\*) from logs limit 1);`

Thanks.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by chaudum** [comment]
Hi @nicetip 
Happy new year, also! Yes, we are aware of this behaviour.

> ORDER BY, LIMIT and OFFSET can only be applied after the last SELECT statement of the UNION ALL, as they are applied to the complete result of the UNION operation. In order to apply an ORDER BY and/or LIMIT and/or OFFSET to any of the partial SELECT statements, those statements need to become subqueries. https://crate.io/docs/crate/reference/en/latest/sql/statements/select.html#sql-reference-union

Writing the individual SELECT statements of the UNION as subselects may not be completely "straightforward", however, it's not difficult either ;-) Making it possible to write individual SELECTS in parenthesis in order to be able to apply a LIMIT/OFFSET on them is very much syntactical sugar and not missing functionality. Of course user experience is important for us, but we also only have limited resources and that's why we think that adding support for that is not that important for us. Hope this is understandable :)
However, if you want to contribute this feature, we are more than happy with also supporting you.

**Comment by nicetip** [comment]
OK, I'll use so. I understand.
Anyway, union is great new feature.
Thanks.

**Comment by mxm** [comment]
The `LIMIT` of a `UNION` has to come last, this is how `UNION` is defined in the SQL standard. If you want to limit one of the union-ed relations, you have to use a subquery (like you proposed). I think this issue can be closed.
