### ISSUE TITLE
How to multiple file import in cratedb(.json) file

### ISSUE THREAD

**Issue by vishuPPatel** [crate/crate#6716]
we crated one directory and name xyz and add the four file added in but bellow writes command is not work.!!!!

**copy mqtt.vishal from '/Do/crate-2.2.4/crate-2.2.4/xyz/*' with (bulk_size = 4);**

This error is Rising
SQLActionException[SQLParseException: Illegal char <*> at index 34: /Do/crate-2.2.4/crate-2.2.4/xyz/*]

SQLActionException: BAD_REQUEST 4000 SQLParseException: Illegal char <*> at index 34: /Do/crate-2.2.4/crate-2.2.4/xyz/*
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:183)
	at io.crate.exceptions.SQLExceptions.createSQLActionException(SQLExceptions.java:124)

**Comment by mikethebeer** [comment]
This exception is raised because CrateDB cannot parse your specified `.json` files. Be sure that your data definition is in form of e.g.

```
{"id": 1, "quote": "Don't panic"}
{"id": 2, "quote": "Ford, you're turning into a penguin. Stop it."}
```

See https://crate.io/docs/crate/reference/en/latest/general/dml.html#importing-data

**Comment by vishuPPatel** [comment]
here i have more then one file that we have to use this command 

in this documentation 

copy quotes from '/tmp/import_data/*' with (bulk_size = 4);

My side

copy mqtt.vishal from '/Do/crate-2.2.4/crate-2.2.4/xyz/*' with (bulk_size = 4);


same as define on document we using the data in our side problem is accrued?

**Comment by mxm** [comment]
The issue is that your data is not formatted correctly. Perhaps you could provide a sample of your data?

**Comment by mikethebeer** [comment]
@vishuPPatel Can you be a bit more precise what you mean with

> same as define on document we using the data in our side problem is accrued?

Please try to narrow down your problem and try a simple `copy from` import from a `tmp` folder on your file system. 

```
copy mqtt.vishal from `/tmp/*.json*`
```

Please ensure that this folder is accessible for the user `crate` (or do `chown` or `chmod` otherwise). It seems that your sql statement is not correctly parsed because of an invalid character that you have provided there.

**Comment by vishuPPatel** [comment]
=======================================================================
                                             This work for the single file data Command
=======================================================================
copy quotes from 'file:///tmp/import_data/quotes.json';

i write this command for the single file data insert that data insert in table 
copy mqtt.vishal from '/Do/crate-2.2.4/crate-2.2.4/xyz/Demo.json';


=======================================================================
                                             This not work for the multile file data Command
=======================================================================
here i have 24 file for the(Demo1,Demo2,Demo3............Demo24)

In this document given command 

copy quotes from '/tmp/import_data/qu*.json';

copy quotes from '/tmp/import_data/*' with (bulk_size = 4);

write for the single command (import the file )by 24 file import one by one all the record get the but i want to insert one command throw Import the multiple file (data) in single command i try below mention command but is not working....!!!!

**and my side of i Import the multiple file(Demo1 To Demo24)

copy quotes from '/tmp/import_data/Dem*.json';

copy mqtt.vishal from '/Do/crate-2.2.4/crate-2.2.4/*' with (bulk_size = 24);**

**Comment by mikethebeer** [comment]
@vishuPPatel Can you define the OS that you are running Crate on (Linux, Windows, OSX, etc.) since the URI path format varies on different OS. I just tried to reproduce your issue however with no success. What I recognize in your description is that you might understand the `bulk_size` a bit wrong. The `bulk_size` defines the number of records that are inserted with one batch. It has nothing to do with the number of files that you want to insert. So I would recommend to remove the `bulk_size` definition in general.

Here you have an example to see how you could use wildcards to include and insert multiple files at once.

On Linux:

```sql
cr> copy countries to directory '/mnt/d/sandbox/crate-2.3.0-SNAPSHOT-3f0657463';
COPY OK, 100000 rows affected  (1.534 sec)
cr> delete from countries;
DELETE OK, 100000 rows affected  (0.917 sec)
cr> copy countries from '/mnt/d/sandbox/crate-2.3.0-SNAPSHOT-3f0657463/countries_*_.json';
COPY OK, 100000 rows affected  (4.323 sec)
```

On Windows:

```sql
cr> copy countries to directory 'file:/D:/sandbox/crate-2.3.0-SNAPSHOT-3f0657463';
COPY OK, 100000 rows affected  (1.323 sec)
cr> delete from countries;
DELETE OK, 100000 rows affected  (0.917 sec)
cr> copy countries from 'file:///D:/sandbox/crate-2.3.0-SNAPSHOT-3f0657463/countries_*_.json';
COPY OK, 24961 rows affected  (2.669 sec)
```

**Comment by vishuPPatel** [comment]
Thanks You....@mikethebeer
