### ISSUE TITLE
Can something else unique other than sha be used for blobs?

### ISSUE THREAD

**Issue by CheyenneForbes** [crate/crate#6898]
With my current project I cant calculate a sha hash before adding a file to crate

**Comment by CheyenneForbes** [comment]
does the hash have to be that of the uploaded file? when users post on my platform the post is given an unique id, could this unique ID in the database be used as the "hash" for crate?

**Comment by CheyenneForbes** [comment]
or could something like DigestInputStream be used to calculate the digest of files while they are being uploaded then return the calculated digest in the HTTP response?

**Comment by joemoe** [comment]
hi @CheyenneForbes,

you can use something else than the `SHA` as we don't check it, although this is not tested an documented so we can't provide any support in case of errors there. there is already an issue for calculating the digest on the go. https://github.com/crate/crate/issues/2981

thanks, joe

**Comment by chaudum** [comment]
We don't check the SHA when uploading the blob, however, when retrieving the blob the URL must match the following pattern:
```java
 public static final Pattern BLOBS_PATTERN = Pattern.compile(String.format(Locale.ENGLISH, "^%s/([^_/][^/]*)/([0-9a-f]{40})$", BLOBS_ENDPOINT));
```
See: https://github.com/crate/crate/blob/master/blob/src/main/java/io/crate/protocols/http/HttpBlobHandler.java#L85

**Comment by joemoe** [comment]
hi, actually i was wrong. we are checking the `SHA`, so there is no way atm to achieve what you are aiming for.

**Comment by CheyenneForbes** [comment]
wouldnt it be better (if it can work) for cratedb to create file ids based on UUIDs then return the id in the response?

**Comment by chaudum** [comment]
No, the SHA hashes ensure data consistency, because they uniquely identify the files, and where they are stored within the cluster.

When you upload a file, its chunks are directly stored on the node where they belong to, even if the client is connected to a different node. That's why you need to know the hash upfront. If we would not know the hash upfront, we'd need to store the file in memory (or temporarily on disk) to compute the hash, before moving it to the correct node.

When you download a file, your are also directed to the correct node based on the hash.

**Comment by mfussenegger** [comment]
Given that the question here as been answered I'm closing this, as there is already another issue about this: https://github.com/crate/crate/issues/2981
