### ISSUE TITLE
Cannot divide a double by a float

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6899]
**CrateDB version**: 2.3.2

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

**OS version / environment description**: Ubuntu 16.4

**Problem description**:

We had queries that worked in Crate 2.2, but now error in 2.3. One of the fields returned is calculated by dividing a double by a float. Crate now errors with:

```
SQLActionException[SQLParseException: Cannot cast [float field] to type double]
```

If I cast the float field to a double manually using `CAST`, it works fine. Guessing it's related to the 2.3.1 change `Avoid downcasts in function expressions which could lead to reduced precision.`. It should be upcasting the float in this case though, shouldn't it?

**Steps to reproduce**:

```
SELECT (double_field / float_field) FROM table
```

If that can't reproduce it, I have a more complicated query which more correctly mirrors what we're actually doing.

**Comment by mfussenegger** [comment]
> Guessing it's related to the 2.3.1 change Avoid downcasts in function expressions which could lead to reduced precision.. 

This is related to the breaking change in 2.3.0:

> Columns aren’t implicitly cast to a type anymore. Whenever columns are compared to Literals (e.g. ‘string’, 1, 1.2), these literals will be converted to the column type but not vice-versa. The column can still be manually cast to a type by using a cast function.

(https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/2.3.0.html#breaking-changes)

The follow-up in 2.3.1 was to make this breaking change a bit less impactful.
We generally try to avoid such breaking changes in a non-major feature release. But here we also addressed inconsistency (in some cases we converted `double -> float`, in other's `float -> double`) and we assumed that most users wouldn't be affected by this change. (Unfortunately, we have no data on what kind of queries our users actually do)

> It should be upcasting the float in this case though, shouldn't it?

We choose to avoid doing any implicit column casts because it can have severe consequences for query performance. For example `WHERE x = some_func(?)` where `x` is an integer and `some_func` returns `long` would result in `cast(x as long) = some_func(?)` if we had a simple cast-precedence. This would prevent the index for `x` being used and would become an expensive query.
There would be ways to solve this in code, but we opted for "explicit is better than implicit".

We would like to observe a bit more if this behaviour causes problems for our users before we make further adjustments.

**Comment by SneakyMax** [comment]
Okay thanks for the info @mfusseneggr. It definitely affected us (and our client) but the problem has been fixed now. The behavior seemed like a bug because upcasting to a double is natural in most programming languages, and the error "cannot cast float to double" is a bit misleading because you can definitely do it manually.

**Comment by mfussenegger** [comment]
Based on the feedback we received we've lifted the restrictions again. That will be already in the upcoming `2.3.4` release. 
The solution we've come up with still avoids casts which would slow down queries significantly, but should generally do what a user expects.
