### ISSUE TITLE
a mysql protocol

### ISSUE THREAD

**Issue by yiguolei** [crate/crate#7117]
hi guys, we have implemented a mysql protocol on top of crate, could we add it to crate master?

**Comment by joemoe** [comment]
hi @yiguolei,

this sounds interesting. do you have a fork repo where we could have a look at the implementation.
our strategy is to fully support the postgres protocol and also be as close as possible to the postgres sql dialect. we probably won't merge this into master as this would add a lot of additional requirements for testing, maintenance and further efforts. but there might be other options.
it would helpful to have the details of the implementation by hand in a repo or as a pr, so that we can have further discussions.

thanks,
joe

**Comment by mxm** [comment]
That sounds very interesting, we'd be curious to have a look! :)

**Comment by chaudum** [comment]
@yiguolei Is this your implementation of the MySQL protocol? https://github.com/baidu/Elasticsearch/tree/ba39b50f13711f0b04049e66288d3afd2e33f83d/src/main/baidu/java/org/elasticsearch/mysql
You mention that you're using CrateDB 0.55, which is really outdated. I guess it would be quite an effort to port this to the current master. However, it would be very interesting. Let us know if you need any help to kick-start this.
