### ISSUE TITLE
killing heavy query

### ISSUE THREAD

**Issue by nicetip** [crate/crate#7122]
**CrateDB version**: 2.3.5

**Environment description**: CentOS Linux release 7.4.1708 (Core)

**Problem description**:

I know it's possible to kill a query using "kill $query_id".
But when I executed a very heavy query, for example sorting with timestamp about million records, I can't query "select * from sys.jobs".
So It's impossible to kill a query.
How could I solve this?
Please let me know.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @nicetip,

we are aware of that issue and looking into possible solutions. depending on the findings one of the next versions might be more resilient in such cases. i'll keep you posted.

thanks, 
joe

**Comment by nicetip** [comment]
I have a idea about this,
In my case, I'm using go-crate library.
And that library is using "_sql" web API.
By exposing, JOB-ID in _sql API's response, It's possible to kill that I executed query.
Thanks.

**Comment by joemoe** [comment]
yes, this might be an option.

**Comment by mfussenegger** [comment]
Wouldn't it be possible to filter `sys.jobs` by the statement? `select id from sys.jobs where stmt = ?` where `?` will be your heavy query.

> By exposing, JOB-ID in _sql API's response, It's possible to kill that I executed query.

The client receives a response only after the query is finished. So it's not that easy as just including the jobId in the response.
We'd have to introduce result streaming so that we can send some information upfront. This would be a major change which also requires changes in the clients.
