### ISSUE TITLE
INGESTION RULES FOR KAFKA

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7459]
Kafka play a significant role in streaming data system.
At present,the information center basically uses Kafka as the streaming hub.
So expect crate support kafka borker like mqtt
e.g.
CREATE INGEST RULE kafka_humidity_rule
ON kafka
WHERE topic like '%humidity%'
INTO kafka_humidity;
This feature is more important in the enterprise. 
Thanks!

**Comment by chaudum** [comment]
At the moment we do not have any plans to support additional streaming protocols, such as the Kafka Protocol.

**Comment by mfussenegger** [comment]
We removed the INGEST rule functionality a while ago.

To get data from Kafka into CrateDB we're improving the SQL compatibility so that tools like [kafka-connect-jdbc](https://docs.confluent.io/current/connect/kafka-connect-jdbc/index.html) work.

You can find known issues for kafka-connect-jdbc [here](https://github.com/crate/crate/issues?q=is%3Aissue+is%3Aopen+label%3A%22tool%3A+Kafka-connect-jdbc%22)
