### ISSUE TITLE
jdbc insert timestam filed loss 8 hours 

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7554]
1.
create table test1(sysdate timestamp) and insert into table test1 date value using jdbc preparestatment.the result lossing 8 hours than os time!
2.
SELECT DATE_FORMAT('%Y-%m-%d %H:%i:%s',CURRENT_TIMESTAMP);
query result slower 8 hours than os time!
How to set the default timezone value 'Asia/Shanghai' in yml or startup shell scrip or  jdbc properties.
Otherwise, the operation of the date field is too tedious.
thanks a lot.

**Comment by cmdares** [comment]
it is too tedious. I wanna crate can be default support timezone setting.

**Comment by mfussenegger** [comment]
We've currently no plans to support setting the timezone or picking up the system time zone.
We would probably accept contributions in that direction (but please open up an issue/dummyPR first to discuss a proposal before starting any work that we might not be able to accept)

There are multiple reasons:

 - Cross datacenter clusters might have different system timezones. This would lead to strange behaviour if we picked up the system defaults.
 - Timezone handling usually needs to be done as part of an application anyway. It is common practice to store a neutral format / include the TZ info in the database. So that users can be shown *their* local time. Using the timezone of the server is not the right thing to do in most cases. This may be a bit opinionated, but we focus our resources on things that are more generally useful. (Hence why we'd probably still accept contributions in this direction)
