### ISSUE TITLE
copy to Exporting 15 billion data resulted in server downtime and 128G of memory was exhausted (8 servers)

### ISSUE THREAD

**Issue by xiaojiazu** [crate/crate#8037]
sql : copy to 
server  memory：128G 
crate CRATE_HEAP_SIZE : 6g   
Export 15 billion data, eat up server memory, resulting in server downtime, what is the reason? Is it caused by query caching? How do I close the cache? elasticsearch cache cleanup API available? Http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-clearcache.html

thanks

**Comment by seut** [comment]
@xiaojiazu Can you please add more information like steps to reproduce, logs, all the information we're asking by our issue template? As the query cache is configured to use only 10% of available HEAP by default, I doubt that this is related to query caching at all.

**Comment by xiaojiazu** [comment]
@seut   If it's convenient, you can import a lot of data, such as 10 billion pieces of data, and execute the copy to command to observe the changes in Linux memory. Out-of-heap memory keeps rising and memory leaks are suspected.

**Comment by xiaojiazu** [comment]
@seut We tried to modify the   source code,"FileWriterCountCollector.java", tried a lot of experiments, but did not solve the problem, I hope the official positioning of the problem. Thanks

**Comment by seut** [comment]
@xiaojiazu That is interesting but won't help in any way without the information we are asking for. Also debugging with 10 billion records it quite time intensive, so tracking down this issue a bit more using detailed information would help.
On memory issues like this, a heapdump would also be very helpful. Please always report in detail to help us debugging/reproducing.

**CrateDB version**:


**Environment description**:

 - JVM version: java -version 
 - Kernel: uname -a
 - Distribution: cat /etc/os-release
 - Number of nodes; Please mention special master/data/client node configuration

If using docker:

 - Docker: docker \-\-version
 - Problem can be reproduced without docker: 
    - [ ] yes
    - [ ] no -> Consider reporting the issue in https://github.com/crate/docker-crate instead



**Problem description**:

Please be precise about errors. Instead of saying "doesn't work" or "fails",
describe the behavior you're observing and what you'd expect to see.

Include relevant logs and error messages or stacktraces if possible.

If there are memory issues please provide the garbage collection log file if
possible.


**Steps to reproduce**:

Please include table schema and some sample records and the statements
that lead to the problem.

**Comment by xiaojiazu** [comment]
@seut  Okay, I'll sort out the documents as you require and send them to you later.
