### ISSUE TITLE
copy to command do not respecting endpoint param

### ISSUE THREAD

**Issue by piedro** [crate/crate#8331]
**Use case**:
copy to command does not respect endpoint param
**Feature description**:
I just want to configure the AWS endpoint  such as  CREATE REPOSITORY  features;
~~~~~~
CREATE REPOSITORY xxxcatedb TYPE s3 WITH (bucket='xxxratedb', endpoint='https://s3.cn-north-1.amazonaws.com.cn/', protocol='https')
~~~~
I just find doc on the https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-to.html#where-clause

but I can't do it, currently, copy to command only support 
s3://[<accesskey>:<secretkey>@]<bucketname>/<path>
please help us as soon as you can.

**Comment by seut** [comment]
We clearly state at https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-to.html#output-uri:

`Additionally, versions prior to 0.51.x use HTTP for connections to S3. Since 0.51.x these connections are using the HTTPS protocol. Please make sure you update your firewall rules to allow outgoing connections on port 443.`

So just use `s3` uri scheme.
