### ISSUE TITLE
Kubernetes Docs improvement 

### ISSUE THREAD

**Issue by bhargavtruecom** [crate/crate#8499]
**CrateDB version**:
Latest

**Environment description**:

**Problem description**:

I went though [https://crate.io/a/run-your-first-cratedb-cluster-on-kubernetes-part-one/](url)
land looks good but doesn't mention how to connect with app ?

I tried to connect with various like
````
crate-0.crate-internal-service.crate.svc.cluster.local:5432,crate-1.crate-internal-service.crate.svc.cluster.local:5432,crate-2.crate-internal-service.crate.svc.cluster.local:5432
```` 
OR
````
crate://crate-0:5432,crate-1:5432/db
````
But none of them working.  Exception was Unknown host. But when i tried with pods ip it was working... so ideally we have to connect with service or with pods name?

Pods and service out put

````
NAME          READY   STATUS    RESTARTS   AGE   IP               NODE          NOMINATED NODE   READINESS GATES
pod/crate-0   1/1     Running   0          35m   192.168.47.232   kubernetes9   <none>           <none>
pod/crate-1   1/1     Running   0          35m   192.168.47.231   kubernetes9   <none>           <none>
pod/crate-2   1/1     Running   0          34m   192.168.47.230   kubernetes9   <none>           <none>

NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE   SELECTOR
service/crate-external-service   LoadBalancer   10.102.81.104    <pending>     4200:30697/TCP,5432:31401/TCP   35m   app=crate
service/crate-internal-service   ClusterIP      10.108.203.218   <none>        4300/TCP                        35m   app=crate

````

When i connect with Loadbalancer ip it was working

````
crate://10.102.81.104:5432/raystatistic

````

, but when i replace with service 
````
crate://crate-external-service:5432/raystatistic
````

it was not working

**Comment by autophagy** [comment]
Hi @bhargavtruecom. It's tricky to help with this since how exactly the load balancer is exposed with a DNS name is quite specific to what infrastructure, or cloud provider, that you're deploying Kubernetes on. In the blogpost, in the case of minikube, this is done by:
```
$ minikube service list --namespace crate
```
If you were deploying kubernetes on, say, azure, it would be different (see: https://blog.jreypo.io/containers/microsoft/azure/cloud/cloud-native/how-to-expose-your-kubernetes-workloads-on-azure/).

The DNS name of `crate-external-service` works within kubernetes (you should be able to access this DNS name within a container deployed within the namespace, for example). But to expose the load balancer externally is dependant on your cloud/kubernetes provider.

What are you using to deploy kubernetes? I could try and point you in the direction of helpful documentation in that case.

**Comment by bhargavtruecom** [comment]
> The DNS name of `crate-external-service` works within kubernetes (you should be able to access this DNS name within a container deployed within the namespace, for example). But to expose the load balancer externally is dependant on your cloud/kubernetes provider.

I dont want to expose it externally... everything is running in kube cluster. so i would i access ? without external loadbalancer ?

**Comment by autophagy** [comment]
@bhargavtruecom Ah, I see - sorry for the misunderstanding. It *should* work to reference the service name, as long as the pod you're referencing it from is within the same namespace. Are you able to use `curl` within a pod you've deployed to determine whether the `crate-external-namespace` address is recognised as a valid one?
