### ISSUE TITLE
COPY FROM ignore filed case

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8552]
create table tbla(a string,b sting);

demoinfo.json
{"A": “1”, "B": "xxx"}
{"A": “2”, "B": "yyy"}

COPY  tbla FROM 'file:///data/demoinfo.json'
and the result
----a---b---A----B----
     null,null,1,xxx
     null,null,2,yyy

Can you ignore case, depending on the database table field?
and when the field is not in table and table options dynamic=true，then new filed name in the table will be use the file filed name.
thanks.

**Comment by seut** [comment]
The SQL-92 standard specifies that identifiers and keywords are case-insensitive and so does CrateDB behave. Since CrateDB 4.0, the default column policy for tables change to `strict`, so the copy from command would fail when unknown column names are used.
This should solve the issue.

Otherwise please explain us a bit more about your use case and how you'd like it to archive.
