### ISSUE TITLE
What happens if vm.max_map_count is ~65 K

### ISSUE THREAD

**Issue by ilarimikkonen** [crate/crate#9178]
**Use case**: we are running an environment where the are lot of docker hosts. Running vm.max_map_count=262144 does not look tempting for us. What happens if we lower the value (change the bootstrap checks) to ~65k? Why is this 262144 ?

Is there any alternative for this?

**Comment by marregui** [comment]
Cratedb uses mmapfs by default (index shard on file system maps to MMapDirectory), governed by config setting 

```node.store.allow_mmap: true```

Under the hood, lucene's MMapDirectory maps in portions of 1G, and thus the number of mappings is dependent on the number of files in the index dir, as well as their size. The limit's default is 65K, and we ask that you raise it by a factor of x4 if you require to use mmapfs. There is absolutely no impact on memory footprint or performance for processes that use the same number of maps. On the other hand, processes where one of the memory mapping functions would have failed with ENOMEM because of hitting the limit, will now be allowed to consume the additional kernel memory.  Each mapped area needs some kernel memory, at least a vm_area_struct must be allocated, i.e. around 128 bytes per map count (plus some small overhead added by the SLAB allocator if additional slabs are needed). When vm.max_map_count is larger, processes are allowed to make the kernel allocate more memory for this purpose, but memory is only allocated with the process actually needs the map areas. 

The alternative is to disable mmapfs:

```node.store.allow_mmap: false```

in which case the store type will be niofs (https://stackoverflow.com/questions/10500811/difference-between-fsdirectory-and-mmap-directory).

**Comment by ilarimikkonen** [comment]
cheers, thanks for the quick reply. We'll give the niofs it a go.

**Comment by lazy-developer** [comment]
Hello @marregui, we tried this option "-Cnode.store.allow_mmapfs=false" but it didn't work. Is it because we're using crate 2.3? Following is the error:-

quantumleapcrate_1  | [2019-09-27T11:31:02,288][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [Grande Ruine] uncaught exception in thread [main]
quantumleapcrate_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [node.store.allow_mmapfs] please check that any required plugins are installed or `license.enterprise` is enabled, if the plugin(s) require(s) it, or check the breaking changes documentation for removed settings

Since which version this option is supported?
Thank you.

**Comment by marregui** [comment]
Hi @lazy-developer ,

2.3? would you consider upgrading? we are at the moment on 4.X.X, as per:

https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/
https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/unreleased.html?highlight=unreleased

Our current master provides the above config parameter.

Best

**Comment by lazy-developer** [comment]
@marregui First of all thanks a lot for your response.
Secondly, we have upgraded to 4.0.4, but we have the practice to update the base image while building the docker container. In our case, our docker-compose file has the "build" section and we call the following Dockerfile from it:-
FROM crate:4.0.4
RUN yum update -y

But when I try to make it up, I get the following error:-
Building quantumleapcrate
Step 1/2 : FROM crate:4.0.4
4.0.4: Pulling from library/crate
Digest: sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Status: Downloaded newer image for crate:4.0.4
 ---> f51b4ea4d182
Step 2/2 : RUN yum update -y
 ---> Running in c8ab141c0bb5
  File "/usr/bin/yum", line 30
    except KeyboardInterrupt, e:
                            ^
SyntaxError: invalid syntax
ERROR: Service 'quantumleapcrate' failed to build: The command '/bin/sh -c yum update -y' returned a non-zero code: 1

Can you please throw some light on this.
Thank you in advance

**Comment by marregui** [comment]
Hi  @lazy-developer!

I hope you had a great weekend.

Can I please have your docker-compose.yml file, I would like to have a first hand feel for it. 

Thank you!

**Comment by lazy-developer** [comment]
@marregui I had a good weekend, I hope yours was fine too :)
Btw, following is my docker-compose.yml file.

1. docker-compose.yml
version: "2.2"
services:
quantumleapcrate:
        build:
          dockerfile: "./dockerfiles/qlcrate.Dockerfile"
          context: "./"
          args:
            - http_proxy
            - https_proxy
            - no_proxy
        image: "qlcrate"
        command: crate  -Cauth.host_based.enabled=false -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*" -Cnet
work.bind_host=0.0.0.0 -Cnetwork.publish_host=_site_ -Cnode.store.allow_mmapfs=false
        healthcheck:
            test: ["CMD", "curl", "--fail", "--max-time", "25", "http://localhost:4200"]
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - ./data_volumes/quantumleap-crate:/data
        networks:
            - default 
        restart: always

2. ./dockerfiles/qlcrate.Dockerfile
FROM crate:4.0.4
RUN yum update -y

**Comment by marregui** [comment]
Hi @lazy-developer ,

Ok I see!, regarding point 2, please have a look at https://github.com/crate/docker-crate 
You will find in there a Dockerfile, which at the moment builds CrateDB 4.0.5 (latest). As you have been able to experience, we soft link python and python3 to version 3.6, and when you try to build your Dockerfile, yum expects python version 2.7's syntax, resulting in the error. May I suggest that you use our Dockerfile?.

Regarding point 1, please find an updated example here: https://github.com/crate/guide/blob/master/docs/deployment/containers/docker.txt 

This has been updated in response to your report.

Yeah, I had a good weekend :)

**Comment by lazy-developer** [comment]
@marregui Bingo, that is what I did, I used your Dockerfile and it worked. Thanks for everything :)

**Comment by marregui** [comment]
Thank you for using CrateDB, may I ask what you are using it for? what’s the use case?

**Comment by lazy-developer** [comment]
Use case for Crate is to store huge historical data which arrives on frequent basis. To tell you in short, we basically deploy open source IoT FIWARE components into our ecosystem and thereby data storage into crate is on frequent basis.

**Comment by marregui** [comment]
Thank you!

**Comment by lazy-developer** [comment]
Thanks to you :)
