### ISSUE TITLE
Adding column inconsistencies

### ISSUE THREAD

**Issue by bputt** [crate/crate#9283]
**CrateDB version**: 3.3.5

**Environment description**:
CentOS 7.latest and OpenJDK 11

**Problem description**:

When we were adding columns, we would get an error like: ```add column failed due to put mapping file timed out[30s]```...We'd try to add them again and then we'd get ```column already exists```.

Interesting thing is that when issuing READ only queries(```SELECT OR SHOW CREATE TABLE```), the column exists, but when trying to insert data, we get a ```column not found``` exception.

**Steps to reproduce**:

Attempting to add columns to a busy cluster? Enforcing the timeout to occur after 30s of acknowledgement.

How can we fix our table so that we can start ingesting data with the new columns?

**Comment by seut** [comment]
@bputt Does this occur on a partitioned table or a normal one?

**Comment by bputt** [comment]
@seut partitioned

**Comment by mfussenegger** [comment]
This is because in 3.3 there are internally two separate cluster state modifications (once for the meta data of the partitions, once for the partitioned table meta data). We've changed that to a single cluster state modification in master (pending for 4.1, https://github.com/crate/crate/pull/9102)

I think we also made a change in 4.0 already that would mitigate the impact of the two running out of sync (but I'm not sure, maybe that change also happened later)

> How can we fix our table so that we can start ingesting data with the new columns?

Can you try re-running the ALTER TABLE statement?

**Comment by bputt** [comment]
@mfussenegger re-running the alter statement fails saying the column already exists, but trying to insert says the column doesn't exist :/

**Comment by bputt** [comment]
More specific error message when trying to add a column

```
SQLActionException[ProcessClusterEventTimeoutException: failed to process cluster event (create-index-template [NAMESPACE..partitioned.TABLENAME.], cause [api]) within 30s]
```

**Comment by mfussenegger** [comment]
Is there any chance you could update to 4.0? The changes we made there could already help.

If not, we might look into backporting parts of https://github.com/crate/crate/pull/9102 to 4.0

**Comment by bputt** [comment]
we're in the process of re-creating the table and copying the data over ;)
