### ISSUE TITLE
Can we get these keys in the object column?

### ISSUE THREAD

**Issue by asdf2014** [crate/crate#9358]
**Use case**:

Only want get these keys of object

**Feature description**:

Something like this
```sql
SELECT DISTINCT obj.keys FROM t
```

**Comment by mfussenegger** [comment]
Currently there is no built-in method for this, but you could create a javascript UDF to return the keys of an object as array and then use it together with `unnest`  to turn the arrays into rows.

**Comment by asdf2014** [comment]
Good to know, thanks a lot. I will give a try. :+1:

**Comment by asdf2014** [comment]
@mfussenegger I have a question about UDF. Will the operators in UDF be pushed down to the storage layer to ensure efficient performance?

**Comment by mfussenegger** [comment]
If I understand your question correctly the short answer is no.
If they're used in the `WHERE` clause they won't utilize the index structures. But they can utilize the query cache in some cases. (So that sub-sequent executions are fast)


If your UDF will only be part of the select-list it usually has little impact on performance.

In your specific case we'd also load the value parts of the object, which of course has some costs. But we defer the value lookup as much as possible. So if the result set is already sufficiently reduced the impact will not matter.

But if you do for example a GROUP BY on the keys you've extracted than it will be slower than an optimized version would be.

**Comment by proddata** [comment]
```sql
CREATE OR REPLACE FUNCTION skeys("obj" OBJECT)
RETURNS ARRAY(TEXT)
LANGUAGE JAVASCRIPT
as '
function skeys(obj){
  return Object.keys(obj);
}
';
```

**Comment by mfussenegger** [comment]
CrateDB 5.0 adds the `object_keys` function: https://github.com/crate/crate/pull/12469
